---
- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
        - yamllint
        - python-black
    gate:
      jobs:
        - flake8
        - yamllint
        - python-black
    periodic-daily:
      jobs:
        - flake8
        - yamllint
        - python-black
