---
- job:
    name: release-tox-drift-test
    parent: tox
    vars:
      tox_envlist: drift-test

- job:
    name: release-tox-drift
    parent: tox
    vars:
      tox_envlist: drift

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
        - yamllint
        - python-black
        - release-tox-drift-test
    periodic-daily:
      jobs:
        - flake8
        - yamllint
        - python-black
        - release-tox-drift-test
        - release-tox-drift
