[tox]
skipsdist = true
envlist = drift-test

[testenv:drift-test]
basepython = python3
deps = -r requirements.txt
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    pytest {posargs:tests/ -v}

[testenv:drift]
basepython = python3
deps = -r requirements.txt
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    python3 src/check-drift.py {posargs:--group all}
