---
manager_version: '9.0.0'

ansible_version: '11.4.0'
ansible_core_version: '2.18.4'

defaults_version: 'v0.20250407.0'
generics_version: 'v0.20250408.0'
manager_playbooks_version: 'v0.20250407.0'
operations_version: 'v0.20250407.0'
playbooks_version: 'v0.20250407.0'

osism_projects:
  ara: '1.7.2'
  docker: '5:27.5.1'
  osism: '0.20250407.0'
  k3s: 'v1.30.10+k3s1'

docker_images:
  adminer: '5.1.0'
  alerta: '9.0.4'
  ara_server: '1.7.2'
  cgit: '1.2.3'
  dnsdist: '1.9.8'
  dnsmasq: '2.90'
  homer: 'v25.04.1'
  inventory_reconciler: '0.20250408.0'
  fleet: 'v4.66.0'
  mariadb: '11.7.2'
  memcached: '1.6.38-alpine'
  netbox: 'v4.2.2'
  nexus: '3.79.0'
  nginx: '1.27.4-alpine'
  osism: '0.20250407.0'
  osism_ansible: '0.20250408.0'
  osism_kubernetes: '0.20250408.0'
  opentelemetry_collector: '0.123.0'
  pgautoupgrade: '16-alpine'
  phpmyadmin: '5.2.2'
  pushgateway: 'v1.11.0'
  postgres: '16.8-alpine'
  redis: '7.4.2-alpine'
  registry: '3.0'
  scaphandre: '1.0.2'
  squid: '6.1-23.10_beta'
  syft: 'v1.22.0'
  # yamllint disable-line rule:line-length
  openstack_database_exporter: 'v0.4.2'
  tempest: 'latest'
  traefik: 'v3.3.5'
  vault: '1.19.1'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: 'v1.7.1'
  ubuntu22_cis: '1.4.2'

ansible_collections:
  ansible.netcommon: '7.2.0'
  ansible.posix: '2.0.0'
  ansible.utils: '5.1.2'
  cloud.common: '4.0.0'
  community.crypto: '2.26.0'
  community.docker: '4.5.2'
  community.general: '10.5.0'
  community.grafana: '2.1.0'
  community.hashi_vault: '6.2.0'
  community.mysql: '3.13.0'
  community.network: '5.1.0'
  community.rabbitmq: '1.4.0'
  community.zabbix: '3.3.0'
  containers.podman: '1.16.3'
  debops.debops: '3.2.4'
  netbox.netbox: '3.21.0'
  openstack.cloud: '2.4.1'
  osism.commons: '0.20250407.0'
  osism.services: '0.20250407.0'
  osism.validations: '0.20250407.0'
  purestorage.flasharray: '1.34.1'
