---
ansible_version: '>=2.10,<2.11'
manager_version: latest
repository_version: latest

osism_projects:
  ara: 1.5.1
  docker: 5:19.03.8
  mitogen: 0.2.9

docker_images:
  adminer: 4.7
  aptly: 1.4.0
  ara_server: 1.5.1
  ara_web: 1.0.0
  installer: latest
  mariadb: 10.4
  netbox: v2.8
  nexus: 3.23.0
  nginx: 1.18-alpine
  phpmyadmin: 5.0
  postgres: 12-alpine
  redis: 6-alpine
  registry: 2.7

ansible_roles:
  ANXS.apt: f602ba7e88abfbb3af6679a8ca47207dc3e9d9c4
  ANXS.timezone: 9a77595bf89fc2c255c7c36c18a9cb113911144d
  ANXS.utilities: 8ec75691a6021aa0ba18214bdcba22242c2c5c10
  geerlingguy.dotfiles: master
  hardening: 2093f503a64f213f58f9cab97a10a6f915a02ce9
  osism.docker: master
  osism.manager: master
  osism.network: master
  stackhpc.luks: master
