---
ansible_version: '5.4.0'
defaults_version: main
generics_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  ara: 1.5.7
  docker: 5:20.10.13

docker_images:
  adminer: 4.8.1
  alerta: 8.6.2
  ara_server: 1.5.7
  cgit: latest
  dnsdist: 1.6.1
  homer: 21.09.2
  keycloak: 17.0.0
  mariadb: 10.6.7
  netbox: v3.1.9-ldap
  nexus: 3.38.0
  nginx: 1.21.6-alpine
  phpmyadmin: 5.1.3
  postgres: 14.2-alpine
  redis: 6.2.6-alpine
  registry: '2.8'
  traefik: v2.6.1
  vault: 1.9.4
  zookeeper: 3.7.0
  zuul_executor: 4.11.0
  zuul_nodepool_launcher: 4.4.0
  zuul_scheduler: 4.11.0
  zuul_web: 4.11.0

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e4b55822cf1bf12f205d3b7d08dcdb634c2f505f
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master
ansible_collections:
  ansible.netcommon: '2.6.1'
  ansible.posix: '1.3.0'
  arista.cvp: '3.3.0'
  arista.eos: '4.1.1'
  community.general: '4.5.0'
  community.network: '3.0.0'
  community.zabbix: '1.5.1'
  debops.debops: '3.0.1'
  netbox.netbox: '3.4.0'
  openstack.cloud: '1.5.3'
  osism.commons: main
  osism.services: main
  osism.validations: main
  stackhpc.cephadm: master
  juniper.device: '1.0.1'
