---
ansible_version: '5.5.0'
defaults_version: main
generics_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  ara: '1.5.7'
  # renovate: datasource=github-releases depName=moby/moby
  docker: '5:20.10.13'

docker_images:
  # renovate: datasource=docker depName=adminer
  adminer: '4.8.1'
  # renovate: datasource=docker depName=alerta/alerta-web
  alerta: '8.7.0'
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara_server: '1.5.7'
  # renovate: datasource=docker depName=clearlinux/cgit
  cgit: latest
  # renovate: datasource=docker depName=quay.io/osism/dnsdist
  dnsdist: '1.6.1'
  # renovate: datasource=docker depName=quay.io/osism/homer
  homer: '21.09.2'
  inventory_reconciler: 'latest'
  # renovate: datasource=docker depName=quay.io/keycloak/keycloak
  keycloak: '17.0.1-legacy'
  # renovate: datasource=docker depName=mariadb
  mariadb: '10.8.2'
  # renovate: datasource=docker depName=quay.io/osism/netbox
  netbox: 'v3.1.9-ldap'
  # renovate: datasource=docker depName=quay.io/osism/nexus
  nexus: '3.38.0'
  # renovate: datasource=docker depName=nginx
  nginx: '1.21.6-alpine'
  osism: 'latest'
  # renovate: datasource=docker depName=phpmyadmin/phpmyadmin
  phpmyadmin: '5.1.3'
  # renovate: datasource=docker depName=postgres
  postgres: '14.2-alpine'
  # renovate: datasource=docker depName=redis
  redis: '6.2.6-alpine'
  # renovate: datasource=docker depName=registry
  registry: '2.8'
  # renovate: datasource=docker depName=traefik
  traefik: 'v2.6.2'
  # renovate: datasource=docker depName=hashicorp/vault
  vault: '1.10.0'
  # renovate: datasource=docker depName=zookeeper
  zookeeper: '3.8.0'
  # renovate: datasource=docker depName=zuul/zuul-client
  zuul_client: '5.0.0'
  # renovate: datasource=docker depName=zuul/zuul-executor
  zuul_executor: '5.0.0'
  # renovate: datasource=docker depName=zuul/nodepool-builder
  zuul_nodepool_builder: '5.0.0'
  # renovate: datasource=docker depName=zuul/nodepool-launcher
  zuul_nodepool_launcher: '5.0.0'
  # renovate: datasource=docker depName=zuul/zuul-scheduler
  zuul_scheduler: '5.0.0'
  # renovate: datasource=docker depName=zuul/zuul-web
  zuul_web: '5.0.0'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: abef57cf7c3da03f25f942e6ddb7f25afd7fda5f
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master

ansible_collections:
  ansible.netcommon: '2.6.1'
  ansible.posix: '1.3.0'
  arista.cvp: '3.3.1'
  arista.eos: '4.1.1'
  community.general: '4.6.1'
  community.network: '3.1.0'
  community.zabbix: '1.5.1'
  debops.debops: '3.0.2'
  netbox.netbox: '3.6.0'
  openstack.cloud: '1.7.2'
  osism.commons: main
  osism.services: main
  osism.validations: main
  stackhpc.cephadm: master
  juniper.device: '1.0.1'
