---
ansible_version: 5.2.0
defaults_version: main
generics_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  ara: 1.5.7
  docker: 5:20.10.12

docker_images:
  adminer: 4.8.1
  alerta: 8.6.2
  ara_server: 1.5.7
  atlantis: v0.18.0
  awx: 19.4.0
  awxclient: 19.5.0
  boundary: 0.6.2
  dnsdist: 1.6.1
  homer: 21.09.2
  keycloak: 16.1.0
  mariadb: 10.6.5
  netbox: v3.1.6-ldap
  nexus: 3.37.3
  nginx: 1.21.5-alpine
  phpmyadmin: 5.1.1
  postgres: 14.1-alpine
  redis: 6.2.6-alpine
  registry: '2.7'
  traefik: v2.5.4
  vault: 1.9.0

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e4b55822cf1bf12f205d3b7d08dcdb634c2f505f
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master
ansible_collections:
  ansible.netcommon: 2.5.0
  ansible.posix: main
  arista.cvp: 3.2.0
  arista.eos: 4.0.0
  awx.awx: 19.4.0
  community.general: main
  community.network: main
  community.zabbix: main
  debops.debops: 2.3.3
  netbox.netbox: devel
  openstack.cloud: master
  osism.commons: main
  osism.services: main
  osism.validations: main
  stackhpc.cephadm: master
  juniper.device: 1.0.1
