---
manager_version: latest

# renovate: datasource=pypi depName=ansible
ansible_version: '11.7.0'
# renovate: datasource=pypi depName=ansible-core
ansible_core_version: '2.18.7'

# renovate: datasource=github-tags depName=osism/defaults
defaults_version: 'v0.20250711.0'
# renovate: datasource=github-tags depName=osism/cfg-generics
generics_version: 'v0.20250709.0'
# renovate: datasource=github-tags depName=osism/ansible-playbooks-manager
manager_playbooks_version: 'v0.20250602.0'
# renovate: datasource=github-tags depName=osism/kolla-operations
operations_version: 'v0.20250530.0'
# renovate: datasource=github-tags depName=osism/ansible-playbooks
playbooks_version: 'v0.20250710.0'

osism_projects:
  # renovate: datasource=docker depName=registry.osism.tech/osism/ara-server
  ara: '1.7.2'
  # renovate: datasource=github-releases depName=moby/moby
  docker: '5:27.5.1'
  # renovate: datasource=pypi depName=osism
  osism: '0.20250709.0'
  # renovate: datasource=github-releases depName=k3s-io/k3s
  k3s: 'v1.33.2+k3s1'

docker_images:
  # renovate: datasource=docker depName=adminer
  adminer: '5.3.0'
  # renovate: datasource=docker depName=alerta/alerta-web
  alerta: '9.0.4'
  # renovate: datasource=docker depName=registry.osism.tech/osism/ara-server
  ara_server: '1.7.2'
  # renovate: datasource=docker depName=registry.osism.tech/osism/cgit
  cgit: '1.2.3'
  # renovate: datasource=docker depName=registry.osism.tech/osism/dnsdist
  dnsdist: '1.9.8'
  # renovate: datasource=docker depName=registry.osism.tech/osism/dnsmasq-osism
  dnsmasq: '2.91'
  # renovate: datasource=docker depName=registry.osism.tech/osism/homer
  homer: 'v25.05.2'
  # renovate: datasource=docker depName=registry.osism.tech/osism/inventory-reconciler
  inventory_reconciler: '0.20250711.0'
  # renovate: datasource=docker depName=fleetdm/fleet
  fleet: 'v4.70.1'
  # renovate: datasource=docker depName=registry.osism.tech/osism/gnmic
  gnmic: '0.41.0'
  # renovate: datasource=docker depName=mariadb
  mariadb: '11.8.2'
  # renovate: datasource=docker depName=memcached
  memcached: '1.6.38-alpine'
  # renovate: datasource=docker depName=registry.osism.tech/osism/netbox
  netbox: 'v4.3.4'
  # renovate: datasource=docker depName=registry.osism.tech/osism/nexus
  nexus: '3.82.0'
  # renovate: datasource=docker depName=nginx
  nginx: '1.29.0-alpine'
  # renovate: datasource=docker depName=registry.osism.tech/osism/osism
  osism: '0.20250709.0'
  # renovate: datasource=docker depName=registry.osism.tech/osism/osism-ansible
  osism_ansible: '0.20250711.0'
  # renovate: datasource=docker depName=registry.osism.tech/osism/osism-kubernetes
  osism_kubernetes: '0.20250711.0'
  # renovate: datasource=docker depName=otel/opentelemetry-collector-contrib
  opentelemetry_collector: '0.130.0'
  # renovate: datasource=docker depName=pgautoupgrade/pgautoupgrade
  pgautoupgrade: '16-alpine'
  # renovate: datasource=docker depName=phpmyadmin/phpmyadmin
  phpmyadmin: '5.2.2'
  # renovate: datasource=docker depName=prom/pushgateway
  pushgateway: 'v1.11.1'
  # renovate: datasource=docker depName=postgres
  postgres: '16.9-alpine'
  # renovate: datasource=docker depName=redis
  redis: '7.4.5-alpine'
  # renovate: datasource=docker depName=registry
  registry: '3.0'
  # renovate: datasource=docker depName=hubblo/scaphandre
  scaphandre: '1.0.2'
  # renovate: datasource=docker depName=ubuntu/squid
  squid: '6.1-23.10_beta'
  # renovate: datasource=docker depName=anchore/syft
  syft: 'v1.29.0'
  # yamllint disable-line rule:line-length
  # renovate: datasource=docker depName=ghcr.io/vexxhost/openstack-database-exporter
  openstack_database_exporter: 'v0.4.2'
  # renovate: datasource=docker depName=registry.osism.tech/osism/tempest
  tempest: 'latest'
  # renovate: datasource=docker depName=traefik
  traefik: 'v3.4.4'
  # renovate: datasource=docker depName=registry.osism.tech/osism/sonic-vs
  sonic_vs: 'latest'
  # renovate: datasource=docker depName=hashicorp/vault
  vault: '1.20.0'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  # renovate: datasource=github-releases depName=PowerDNS/pdns_recursor-ansible
  pdns_recursor: 'v1.7.1'
  # renovate: datasource=github-tags depName=ansible-lockdown/UBUNTU22-CIS
  ubuntu22_cis: '2.0.0'

ansible_collections:
  # renovate: datasource=galaxy-collection depName=ansible.netcommon
  ansible.netcommon: '8.0.1'
  # renovate: datasource=galaxy-collection depName=ansible.posix
  ansible.posix: '2.1.0'
  # renovate: datasource=galaxy-collection depName=ansible.utils
  ansible.utils: '6.0.0'
  # renovate: datasource=galaxy-collection depName=cloud.common
  cloud.common: '5.0.0'
  # renovate: datasource=galaxy-collection depName=community.crypto
  community.crypto: '3.0.1'
  # renovate: datasource=galaxy-collection depName=community.docker
  community.docker: '4.6.1'
  # renovate: datasource=galaxy-collection depName=community.general
  community.general: '11.1.0'
  # renovate: datasource=galaxy-collection depName=community.grafana
  community.grafana: '2.3.0'
  # renovate: datasource=galaxy-collection depName=community.hashi_vault
  community.hashi_vault: '7.0.0'
  # renovate: datasource=galaxy-collection depName=community.mysql
  community.mysql: '3.14.0'
  # renovate: datasource=galaxy-collection depName=community.network
  community.network: '5.1.0'
  # renovate: datasource=galaxy-collection depName=community.rabbitmq
  community.rabbitmq: '1.6.0'
  # renovate: datasource=galaxy-collection depName=community.zabbix
  community.zabbix: '4.1.0'
  # renovate: datasource=galaxy-collection depName=containers.podman
  containers.podman: '1.17.0'
  # renovate: datasource=galaxy-collection depName=debops.debops
  debops.debops: '3.2.4'
  # renovate: datasource=galaxy-collection depName=fortinet.fortios
  fortinet.fortios: '2.4.0'
  # renovate: datasource=galaxy-collection depName=netbox.netbox
  netbox.netbox: '3.21.0'
  # renovate: datasource=galaxy-collection depName=openstack.cloud
  openstack.cloud: '2.4.1'
  # renovate: datasource=galaxy-collection depName=osism.commons
  osism.commons: '0.20250623.0'
  # renovate: datasource=galaxy-collection depName=osism.services
  osism.services: '0.20250711.0'
  # renovate: datasource=galaxy-collection depName=osism.validations
  osism.validations: '0.20250605.0'
  # renovate: datasource=galaxy-collection depName=purestorage.flasharray
  purestorage.flasharray: '1.36.0'
