---
ansible_version: '>=3.0.0,<4.0.0'
manager_version: latest
repository_version: latest

osism_projects:
  ara: 1.5.5
  docker: 5:20.10.5

docker_images:
  adminer: 4.7
  ara_server: 1.5.5
  awxclient: 19.0.0
  mariadb: 10.5
  netbox: v2.10
  nexus: 3.30.0
  nginx: 1.19-alpine
  phpmyadmin: 5.1
  postgres: 13-alpine
  redis: 6-alpine
  registry: 2.7

ansible_roles:
  ANXS.apt: f602ba7e88abfbb3af6679a8ca47207dc3e9d9c4
  geerlingguy.dotfiles: master
  hardening: e4b55822cf1bf12f205d3b7d08dcdb634c2f505f
  stackhpc.luks: master
  stackhpc.systemd_networkd: master
