---
ansible_version: '5.9.0'
defaults_version: main
generics_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara: '1.5.8'
  # renovate: datasource=github-releases depName=moby/moby
  docker: '5:20.10.17'

docker_images:
  # renovate: datasource=docker depName=adminer
  adminer: '4.8.1'
  # renovate: datasource=docker depName=alerta/alerta-web
  alerta: '8.7.0'
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara_server: '1.5.8'
  # renovate: datasource=docker depName=quay.io/osism/cgit
  cgit: '1.2.3'
  # renovate: datasource=docker depName=quay.io/osism/dnsdist
  dnsdist: '1.6.1'
  # renovate: datasource=docker depName=quay.io/osism/homer
  homer: '22.02.2'
  inventory_reconciler: 'latest'
  # renovate: datasource=docker depName=quay.io/keycloak/keycloak
  keycloak: '18.0.0-legacy'
  # renovate: datasource=docker depName=mariadb
  mariadb: '10.8.3'
  # renovate: datasource=docker depName=memcached
  memcached: '1.6.15-alpine'
  # renovate: datasource=docker depName=quay.io/osism/netbox
  netbox: 'v3.2.4-ldap'
  # renovate: datasource=docker depName=quay.io/osism/nexus
  nexus: '3.39.0'
  # renovate: datasource=docker depName=nginx
  nginx: '1.22.0-alpine'
  docker_openpolicyagent: '0.8'
  # yamllint disable-line rule:line-length
  # renovate: datasource=docker depName=quay.io/sovereigncloudstack/openstack-health-monitor
  openstack_health_monitor: 'v3.0.0'
  osism: 'latest'
  # renovate: datasource=docker depName=quay.io/osism/patchman
  patchman: '2.0.3'
  # renovate: datasource=docker depName=phpmyadmin/phpmyadmin
  phpmyadmin: '5.2.0'
  # renovate: datasource=docker depName=postgres
  postgres: '14.3-alpine'
  # renovate: datasource=docker depName=redis
  redis: '7.0.1-alpine'
  # renovate: datasource=docker depName=registry
  registry: '2.8'
  # renovate: datasource=docker depName=traefik
  traefik: 'v2.7.1'
  # renovate: datasource=docker depName=hashicorp/vault
  vault: '1.10.4'
  # renovate: datasource=docker depName=zookeeper
  zookeeper: '3.8.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_client: '6.0.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_executor: '6.0.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_nodepool_builder: '6.0.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_nodepool_launcher: '6.0.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_scheduler: '6.0.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_web: '6.0.0'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: abef57cf7c3da03f25f942e6ddb7f25afd7fda5f
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master

ansible_collections:
  ansible.netcommon: '3.0.1'
  ansible.posix: '1.4.0'
  arista.cvp: '3.3.1'
  arista.eos: '5.0.1'
  community.general: '5.1.0'
  community.network: '4.0.1'
  community.zabbix: '1.7.0'
  debops.debops: '3.0.2'
  netbox.netbox: '3.7.1'
  openstack.cloud: '1.8.0'
  osism.commons: main
  osism.services: main
  osism.validations: main
  stackhpc.cephadm: master
  juniper.device: '1.0.1'
