---
# renovate: datasource=pypi depName=ansible
ansible_version: '10.3.0'
# renovate: datasource=pypi depName=ansible-core
ansible_core_version: '2.17.3'

defaults_version: main
generics_version: main
manager_playbooks_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara: '1.7.1'
  # renovate: datasource=github-releases depName=moby/moby
  docker: '5:26.1.4'
  # renovate: datasource=pypi depName=osism
  osism: '0.20240825.0'
  # renovate: datasource=github-releases depName=k3s-io/k3s
  k3s: 'v1.30.3+k3s1'

docker_images:
  # renovate: datasource=docker depName=adminer
  adminer: '4.8.1'
  # renovate: datasource=docker depName=alerta/alerta-web
  alerta: '9.0.3'
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara_server: '1.7.1'
  # renovate: datasource=docker depName=quay.io/osism/cgit
  cgit: '1.2.3'
  # renovate: datasource=docker depName=quay.io/osism/dnsdist
  dnsdist: '1.9.6'
  # renovate: datasource=docker depName=quay.io/osism/homer
  homer: 'v24.05.1'
  inventory_reconciler: 'latest'
  # renovate: datasource=docker depName=fleetdm/fleet
  fleet: 'v4.55.1'
  # renovate: datasource=docker depName=quay.io/keycloak/keycloak
  keycloak: '19.0.3-legacy'
  # renovate: datasource=docker depName=mariadb
  mariadb: '11.5.2'
  # renovate: datasource=docker depName=memcached
  memcached: '1.6.29-alpine'
  # renovate: datasource=docker depName=quay.io/osism/netbox
  netbox: 'v4.0.9'
  # renovate: datasource=docker depName=quay.io/osism/nexus
  nexus: '3.71.0'
  # renovate: datasource=docker depName=nginx
  nginx: '1.27.1-alpine'
  osism: 'latest'
  # renovate: datasource=docker depName=phpmyadmin/phpmyadmin
  phpmyadmin: '5.2.1'
  # renovate: datasource=docker depName=prom/pushgateway
  pushgateway: 'v1.9.0'
  # renovate: datasource=docker depName=postgres
  postgres: '16.4-alpine'
  # renovate: datasource=docker depName=redis
  redis: '7.4.0-alpine'
  # renovate: datasource=docker depName=registry
  registry: '2.8'
  # renovate: datasource=docker depName=quay.io/ceph/ceph
  rook_ceph: 'v18.2.2-20240521'
  # renovate: datasource=docker depName=rook/ceph
  rook_operator: 'v1.15.0'
  # renovate: datasource=docker depName=hubblo/scaphandre
  scaphandre: '1.0.0'
  # renovate: datasource=docker depName=ubuntu/squid
  squid: '6.1-23.10_beta'
  # yamllint disable-line rule:line-length
  # renovate: datasource=docker depName=ghcr.io/vexxhost/openstack-database-exporter
  openstack_database_exporter: 'v0.4.2'
  # renovate: datasource=docker depName=quay.io/osism/tempest
  tempest: 'latest'
  # renovate: datasource=docker depName=traefik
  traefik: 'v3.1.2'
  # renovate: datasource=docker depName=hashicorp/vault
  vault: '1.17.3'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: 'v1.7.1'
  proxmox: develop
  ubuntu22_cis: devel

ansible_collections:
  # renovate: datasource=galaxy-collection depName=ansible.netcommon
  ansible.netcommon: '7.1.0'
  # renovate: datasource=galaxy-collection depName=ansible.posix
  ansible.posix: '1.5.4'
  # renovate: datasource=galaxy-collection depName=ansible.utils
  ansible.utils: '5.1.0'
  # renovate: datasource=galaxy-collection depName=cloud.common
  cloud.common: '4.0.0'
  # renovate: datasource=galaxy-collection depName=community.crypto
  community.crypto: '2.21.1'
  # renovate: datasource=galaxy-collection depName=community.docker
  community.docker: '3.12.1'
  # renovate: datasource=galaxy-collection depName=community.general
  community.general: '9.3.0'
  # renovate: datasource=galaxy-collection depName=community.grafana
  community.grafana: '2.1.0'
  # renovate: datasource=galaxy-collection depName=community.hashi_vault
  community.hashi_vault: '6.2.0'
  # renovate: datasource=galaxy-collection depName=community.mysql
  community.mysql: '3.10.0'
  # renovate: datasource=galaxy-collection depName=community.network
  community.network: '5.0.3'
  # renovate: datasource=galaxy-collection depName=community.rabbitmq
  community.rabbitmq: '1.3.0'
  # renovate: datasource=galaxy-collection depName=community.zabbix
  community.zabbix: '3.1.1'
  # renovate: datasource=galaxy-collection depName=containers.podman
  containers.podman: '1.15.4'
  # renovate: datasource=galaxy-collection depName=debops.debops
  debops.debops: '3.1.0'
  # renovate: datasource=galaxy-collection depName=kubernetes.core
  kubernetes.core: '5.0.0'
  # renovate: datasource=galaxy-collection depName=netbox.netbox
  netbox.netbox: '3.19.1'
  # renovate: datasource=galaxy-collection depName=openstack.cloud
  openstack.cloud: '2.2.0'
  osism.commons: main
  osism.services: main
  osism.validations: main

helm_chart_repositories:
  bitnami: https://charts.bitnami.com/bitnami
  cnpg: https://cloudnative-pg.github.io/charts
  codecentric: https://codecentric.github.io/helm-charts
  dnationcloud: https://dnationcloud.github.io/helm-hub
  mariadb-operator: https://mariadb-operator.github.io/mariadb-operator
  rook-release: https://charts.rook.io/release
