---
ansible_version: '9.4.0'
# renovate: datasource=pypi depName=ansible-core
ansible_core_version: '2.16.6'

defaults_version: main
generics_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara: '1.7.1'
  # renovate: datasource=github-releases depName=moby/moby
  docker: '5:24.0.9'
  # renovate: datasource=pypi depName=osism
  osism: '0.20240417.0'
  # renovate: datasource=github-releases depName=k3s-io/k3s
  k3s: 'v1.29.0+k3s1'

docker_images:
  # renovate: datasource=docker depName=adminer
  adminer: '4.8.1'
  # renovate: datasource=docker depName=alerta/alerta-web
  alerta: '9.0.3'
  ara_server: 'latest'
  # renovate: datasource=docker depName=quay.io/osism/cgit
  cgit: '1.2.3'
  # renovate: datasource=docker depName=quay.io/osism/dnsdist
  dnsdist: '1.8.0'
  # renovate: datasource=docker depName=quay.io/osism/homer
  homer: 'v24.04.1'
  inventory_reconciler: 'latest'
  # renovate: datasource=docker depName=fleetdm/fleet
  fleet: 'v4.48.3'
  # renovate: datasource=docker depName=quay.io/keycloak/keycloak
  keycloak: '19.0.3-legacy'
  # renovate: datasource=docker depName=mariadb
  mariadb: '11.3.2'
  # renovate: datasource=docker depName=memcached
  memcached: '1.6.26-alpine'
  netbox: 'latest'
  # renovate: datasource=docker depName=quay.io/osism/nexus
  nexus: '3.67.1'
  # renovate: datasource=docker depName=nginx
  nginx: '1.25.5-alpine'
  openstack_health_monitor: 'v7.0.0'
  osism: 'latest'
  # renovate: datasource=docker depName=phpmyadmin/phpmyadmin
  phpmyadmin: '5.2.1'
  # renovate: datasource=docker depName=postgres
  postgres: '15.6-alpine'
  postgres_upgrade: '14-to-15'
  # renovate: datasource=docker depName=redis
  redis: '7.2.4-alpine'
  # renovate: datasource=docker depName=registry
  registry: '2.8'
  # renovate: datasource=docker depName=hubblo/scaphandre
  scaphandre: '1.0.0'
  # renovate: datasource=docker depName=ubuntu/squid
  squid: '5.7-23.04_beta'
  # renovate: datasource=docker depName=traefik
  traefik: '2.11.2'
  # renovate: datasource=docker depName=hashicorp/vault
  vault: '1.16.1'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: 'v1.6.0'
  proxmox: develop
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master
  ubuntu22_cis: devel

ansible_collections:
  ansible.netcommon: '6.1.1'
  ansible.posix: '1.5.4'
  ansible.utils: '3.0.0'
  cloud.common: '3.0.0'
  community.crypto: '2.16.2'
  community.docker: '3.5.0'
  community.general: '8.6.0'
  community.grafana: '1.6.1'
  community.hashi_vault: '6.1.0'
  community.mysql: '3.8.0'
  community.network: '5.0.2'
  community.rabbitmq: '1.2.3'
  containers.podman: '1.11.0'
  debops.debops: '3.1.0'
  kubernetes.core: '3.0.0'
  netbox.netbox: '3.17.0'
  openstack.cloud: '2.2.0'
  osism.commons: main
  osism.services: main
  osism.validations: main
  stackhpc.cephadm: master

helm_chart_repositories:
  cnpg: https://cloudnative-pg.github.io/charts
  codecentric: https://codecentric.github.io/helm-charts
  dnationcloud: https://dnationcloud.github.io/helm-hub
  kubernetes-dashboard: https://kubernetes.github.io/dashboard
  rook-release: https://charts.rook.io/release
