---
ansible_version: '>=3.0.0,<4.0.0'
ansible_base_version: '>=2.10.0,<2.11.0'
manager_version: latest
repository_version: latest

osism_projects:
  ara: 1.5.6
  docker: 5:20.10.6

docker_images:
  adminer: 4.8.0
  ara_server: 1.5.6
  awxclient: 19.1.0
  mariadb: '10.6'
  netbox: v2.11
  nexus: 3.30.1
  nginx: 1.20-alpine
  phpmyadmin: 5.1.0
  postgres: 13-alpine
  redis: 6-alpine
  registry: '2.7'

ansible_roles:
  ANXS.apt: f602ba7e88abfbb3af6679a8ca47207dc3e9d9c4
  geerlingguy.dotfiles: master
  hardening: e4b55822cf1bf12f205d3b7d08dcdb634c2f505f
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master
