---
ansible_base_version: '>=2.10.0,<2.11.0'
ansible_version: '>=3.0.0,<4.0.0'
defaults_version: main
generics_version: master
manager_version: latest
playbooks_version: master

osism_projects:
  ara: 1.5.6
  docker: 5:20.10.7

docker_images:
  adminer: 4.8.1
  ara_server: 1.5.6
  awxclient: 19.2.2
  mariadb: '10.6'
  netbox: v2.11.9-ldap
  nexus: 3.32.0
  nginx: 1.21-alpine
  phpmyadmin: 5.1.1
  postgres: 13.3-alpine
  redis: 6.2.4-alpine
  registry: '2.7'
  keycloak: 14.0.0

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e4b55822cf1bf12f205d3b7d08dcdb634c2f505f
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master
ansible_collections:
  ansible.netcommon: 2.2.0
  ansible.posix: main
  arista.cvp: 3.0.0
  arista.eos: 2.2.0
  awx.awx: 19.2.2
  community.general: main
  community.network: main
  community.zabbix: main
  debops.debops: 2.3.1
  netbox.netbox: devel
  openstack.cloud: master
  osism.commons: master
  osism.services: master
  osism.validations: main
  stackhpc.cephadm: master
