---
ansible_version: '>=3.0.0,<4.0.0'
ansible_base_version: '>=2.10.0,<2.11.0'
manager_version: latest
repository_version: latest

osism_projects:
  ara: 1.5.6
  docker: 5:20.10.7

docker_images:
  adminer: 4.8.1
  ara_server: 1.5.6
  awxclient: 19.2.2
  mariadb: '10.6'
  netbox: v2.11
  nexus: 3.31.1
  nginx: 1.21-alpine
  phpmyadmin: 5.1.1
  postgres: 13.3-alpine
  redis: 6-alpine
  registry: '2.7'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e4b55822cf1bf12f205d3b7d08dcdb634c2f505f
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master

ansible_collections:
  ansible.netcommon: main
  ansible.posix: main
  arista.cvp: devel
  arista.eos: devel
  awx.awx:
  community.general: main
  community.network: main
  community.zabbix: main
  debops.debops: master
  netbox.netbox: devel
  openstack.cloud: master
  osism.commons: master
  osism.services: master
  osism.validations: master
  stackhpc.cephadm: master
