---
ansible_version: 4.6.0
defaults_version: main
generics_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  ara: 1.5.7
  docker: 5:20.10.9

docker_images:
  adminer: 4.8.1
  ara_server: 1.5.7
  awxclient: 19.4.0
  homer: 21.09.2
  keycloak: 15.0.2
  mariadb: 10.6.4
  netbox: v3.0.7-ldap
  nexus: 3.35.0
  nginx: 1.21.3-alpine
  phpmyadmin: 5.1.1
  postgres: 14.0-alpine
  redis: 6.2.6-alpine
  registry: '2.7'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e4b55822cf1bf12f205d3b7d08dcdb634c2f505f
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master
ansible_collections:
  ansible.netcommon: 2.2.0
  ansible.posix: main
  arista.cvp: 3.0.0
  arista.eos: 2.2.0
  awx.awx: 19.2.2
  community.general: main
  community.network: main
  community.zabbix: main
  debops.debops: 2.3.1
  netbox.netbox: devel
  openstack.cloud: master
  osism.commons: main
  osism.services: main
  osism.validations: main
  stackhpc.cephadm: master
