---
# renovate: datasource=pypi depName=ansible
ansible_version: '10.1.0'
# renovate: datasource=pypi depName=ansible-core
ansible_core_version: '2.17.1'

defaults_version: main
generics_version: main
manager_playbooks_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara: '1.7.1'
  # renovate: datasource=github-releases depName=moby/moby
  docker: '5:26.1.4'
  # renovate: datasource=pypi depName=osism
  osism: '0.20240625.0'
  # renovate: datasource=github-releases depName=k3s-io/k3s
  k3s: 'v1.29.2+k3s1'

docker_images:
  # renovate: datasource=docker depName=adminer
  adminer: '4.8.1'
  # renovate: datasource=docker depName=alerta/alerta-web
  alerta: '9.0.3'
  ara_server: 'latest'
  # renovate: datasource=docker depName=quay.io/osism/cgit
  cgit: '1.2.3'
  # renovate: datasource=docker depName=quay.io/osism/dnsdist
  dnsdist: '1.8.0'
  # renovate: datasource=docker depName=quay.io/osism/homer
  homer: 'v24.05.1'
  inventory_reconciler: 'latest'
  # renovate: datasource=docker depName=fleetdm/fleet
  fleet: 'v4.53.1'
  # renovate: datasource=docker depName=quay.io/keycloak/keycloak
  keycloak: '19.0.3-legacy'
  # renovate: datasource=docker depName=mariadb
  mariadb: '11.4.2'
  # renovate: datasource=docker depName=memcached
  memcached: '1.6.29-alpine'
  # renovate: datasource=docker depName=quay.io/osism/netbox
  netbox: 'v3.7.8'
  # renovate: datasource=docker depName=quay.io/osism/nexus
  nexus: '3.69.0'
  # renovate: datasource=docker depName=nginx
  nginx: '1.27.0-alpine'
  openstack_health_monitor: 'v7.0.0'
  osism: 'latest'
  # renovate: datasource=docker depName=phpmyadmin/phpmyadmin
  phpmyadmin: '5.2.1'
  # renovate: datasource=docker depName=postgres
  postgres: '15.7-alpine'
  postgres_upgrade: '14-to-15'
  # renovate: datasource=docker depName=redis
  redis: '7.2.5-alpine'
  # renovate: datasource=docker depName=registry
  registry: '2.8'
  # renovate: datasource=docker depName=quay.io/ceph/ceph
  rook_ceph: 'v18.2.2-20240521'
  # renovate: datasource=docker depName=rook/ceph
  rook_operator: 'v1.14.7'
  # renovate: datasource=docker depName=hubblo/scaphandre
  scaphandre: '1.0.0'
  # renovate: datasource=docker depName=ubuntu/squid
  squid: '5.7-23.04_beta'
  # yamllint disable-line rule:line-length
  # renovate: datasource=docker depName=ghcr.io/vexxhost/openstack-database-exporter
  openstack_database_exporter: 'v0.4.2'
  # renovate: datasource=docker depName=quay.io/osism/tempest
  tempest: 'latest'
  # renovate: datasource=docker depName=traefik
  traefik: 'v3.0.4'
  # renovate: datasource=docker depName=hashicorp/vault
  vault: '1.17.1'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: 'v1.6.0'
  proxmox: develop
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master
  ubuntu22_cis: devel

ansible_collections:
  # renovate: datasource=galaxy-collection depName=ansible.netcommon
  ansible.netcommon: '7.0.0'
  # renovate: datasource=galaxy-collection depName=ansible.posix
  ansible.posix: '1.5.4'
  # renovate: datasource=galaxy-collection depName=ansible.utils
  ansible.utils: '3.0.0'
  # renovate: datasource=galaxy-collection depName=cloud.common
  cloud.common: '4.0.0'
  # renovate: datasource=galaxy-collection depName=community.crypto
  community.crypto: '2.16.2'
  # renovate: datasource=galaxy-collection depName=community.docker
  community.docker: '3.5.0'
  # renovate: datasource=galaxy-collection depName=community.general
  community.general: '9.1.0'
  # renovate: datasource=galaxy-collection depName=community.grafana
  community.grafana: '1.6.1'
  # renovate: datasource=galaxy-collection depName=community.hashi_vault
  community.hashi_vault: '6.1.0'
  # renovate: datasource=galaxy-collection depName=community.mysql
  community.mysql: '3.8.0'
  # renovate: datasource=galaxy-collection depName=community.network
  community.network: '5.0.3'
  # renovate: datasource=galaxy-collection depName=community.rabbitmq
  community.rabbitmq: '1.2.3'
  # renovate: datasource=galaxy-collection depName=containers.podman
  containers.podman: '1.11.0'
  # renovate: datasource=galaxy-collection depName=debops.debops
  debops.debops: '3.1.0'
  # renovate: datasource=galaxy-collection depName=kubernetes.core
  kubernetes.core: '3.0.0'
  # renovate: datasource=galaxy-collection depName=netbox.netbox
  netbox.netbox: '3.19.1'
  # renovate: datasource=galaxy-collection depName=openstack.cloud
  openstack.cloud: '2.2.0'
  osism.commons: main
  osism.services: main
  osism.validations: main
  stackhpc.cephadm: master

helm_chart_repositories:
  bitnami: https://charts.bitnami.com/bitnami
  cnpg: https://cloudnative-pg.github.io/charts
  codecentric: https://codecentric.github.io/helm-charts
  dnationcloud: https://dnationcloud.github.io/helm-hub
  kubernetes-dashboard: https://kubernetes.github.io/dashboard
  mariadb-operator: https://mariadb-operator.github.io/mariadb-operator
  rook-release: https://charts.rook.io/release
