---
ansible_version: '8.7.0'
# renovate: datasource=pypi depName=ansible-core
ansible_core_version: '2.15.5'

defaults_version: main
generics_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara: '1.7.0'
  # renovate: datasource=github-releases depName=moby/moby
  docker: '5:24.0.7'
  # renovate: datasource=pypi depName=osism
  osism: '0.20231203.0'
  # renovate: datasource=github-releases depName=k3s-io/k3s
  k3s: 'v1.28.2+k3s1'

docker_images:
  # renovate: datasource=docker depName=adminer
  adminer: '4.8.1'
  # renovate: datasource=docker depName=alerta/alerta-web
  alerta: '9.0.1'
  ara_server: 'latest'
  # renovate: datasource=docker depName=quay.io/osism/cgit
  cgit: '1.2.3'
  # renovate: datasource=docker depName=quay.io/osism/dnsdist
  dnsdist: '1.8.0'
  # renovate: datasource=docker depName=quay.io/osism/homer
  homer: 'v23.10.1'
  inventory_reconciler: 'latest'
  # renovate: datasource=docker depName=fleetdm/fleet
  fleet: 'v4.43.0'
  # renovate: datasource=docker depName=quay.io/keycloak/keycloak
  keycloak: '19.0.3-legacy'
  # renovate: datasource=docker depName=mariadb
  mariadb: '11.2.2'
  # renovate: datasource=docker depName=memcached
  memcached: '1.6.22-alpine'
  netbox: 'latest'
  # renovate: datasource=docker depName=quay.io/osism/nexus
  nexus: '3.63.0'
  # renovate: datasource=docker depName=nginx
  nginx: '1.25.3-alpine'
  # yamllint disable-line rule:line-length
  # renovate: datasource=docker depName=quay.io/sovereigncloudstack/openstack-health-monitor
  openstack_health_monitor: 'v5.0'
  osism: 'latest'
  # renovate: datasource=docker depName=phpmyadmin/phpmyadmin
  phpmyadmin: '5.2.1'
  # renovate: datasource=docker depName=postgres
  postgres: '15.4-alpine'
  postgres_upgrade: '14-to-15'
  # renovate: datasource=docker depName=redis
  redis: '7.2.3-alpine'
  # renovate: datasource=docker depName=registry
  registry: '2.8'
  # renovate: datasource=docker depName=hubblo/scaphandre
  scaphandre: '0.5.0'
  # renovate: datasource=docker depName=ubuntu/squid
  squid: '5.7-23.04_beta'
  # renovate: datasource=docker depName=traefik
  traefik: '2.10.7'
  # renovate: datasource=docker depName=hashicorp/vault
  vault: '1.15.4'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: 'v1.6.0'
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master
  ubuntu22_cis: devel

ansible_collections:
  ansible.netcommon: '5.3.0'
  ansible.posix: '1.5.4'
  ansible.utils: '2.8.0'
  cloud.common: '2.1.2'
  community.crypto: '2.9.0'
  community.docker: '2.7.3'
  community.general: '7.5.3'
  community.grafana: '1.5.3'
  community.hashi_vault: '3.4.0'
  community.mysql: '3.5.1'
  community.network: '5.0.2'
  community.rabbitmq: '1.2.3'
  containers.podman: '1.10.1'
  debops.debops: '3.1.0'
  kubernetes.core: '2.3.2'
  netbox.netbox: '3.16.0'
  openstack.cloud: '2.2.0'
  osism.commons: main
  osism.services: main
  osism.sonic: main
  osism.validations: main
  stackhpc.cephadm: master
