---
ansible_version: '7.2.0'
ansible_core_version: '2.14.2'

defaults_version: main
generics_version: main
manager_version: latest
operations_version: main
playbooks_version: main

osism_projects:
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara: '1.6.1'
  # renovate: datasource=github-releases depName=moby/moby
  docker: '5:20.10.23'

docker_images:
  # renovate: datasource=docker depName=adminer
  adminer: '4.8.1'
  # renovate: datasource=docker depName=alerta/alerta-web
  alerta: '8.7.0'
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara_server: '1.6.1'
  # renovate: datasource=docker depName=quay.io/osism/cgit
  cgit: '1.2.3'
  # renovate: datasource=docker depName=quay.io/osism/dnsdist
  dnsdist: '1.6.1'
  # renovate: datasource=docker depName=quay.io/osism/homer
  homer: 'v23.02.1'
  inventory_reconciler: 'latest'
  # renovate: datasource=docker depName=fleetdm/fleet
  fleet: 'v4.27.0'
  # renovate: datasource=docker depName=quay.io/keycloak/keycloak
  keycloak: '19.0.3-legacy'
  # renovate: datasource=docker depName=mariadb
  mariadb: '10.10.3'
  # renovate: datasource=docker depName=memcached
  memcached: '1.6.18-alpine'
  # renovate: datasource=docker depName=quay.io/osism/netbox
  netbox: 'v3.4.4'
  # renovate: datasource=docker depName=quay.io/osism/nexus
  nexus: '3.47.1'
  # renovate: datasource=docker depName=nginx
  nginx: '1.23.3-alpine'
  docker_openpolicyagent: '0.8'
  # yamllint disable-line rule:line-length
  # renovate: datasource=docker depName=quay.io/sovereigncloudstack/openstack-health-monitor
  openstack_health_monitor: 'v3.0.0'
  osism: '0.9.6'
  # renovate: datasource=docker depName=quay.io/osism/patchman
  patchman: '2.0.8'
  # renovate: datasource=docker depName=phpmyadmin/phpmyadmin
  phpmyadmin: '5.2.1'
  # renovate: datasource=docker depName=postgres
  postgres: '15.2-alpine'
  # renovate: datasource=docker depName=redis
  redis: '7.0.8-alpine'
  # renovate: datasource=docker depName=registry
  registry: '2.8'
  # renovate: datasource=docker depName=ubuntu/squid
  squid: '5.2-22.04_beta'
  # renovate: datasource=docker depName=traefik
  traefik: 'v2.9.6'
  # renovate: datasource=docker depName=hashicorp/vault
  vault: '1.12.3'
  # renovate: datasource=docker depName=zookeeper
  zookeeper: '3.8.1'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_client: '8.1.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_executor: '8.1.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_nodepool_builder: '8.1.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_nodepool_launcher: '8.1.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_scheduler: '8.1.0'
  # renovate: datasource=git-tags depName=https://opendev.org/zuul/zuul.git
  zuul_web: '8.1.0'

ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  stackhpc.libvirt_host: master
  stackhpc.libvirt_vm: master
  stackhpc.luks: master
  stackhpc.systemd_networkd: master

ansible_collections:
  ansible.netcommon: '3.1.3'
  ansible.posix: '1.5.1'
  ansible.utils: '2.8.0'
  cloud.common: '2.1.2'
  community.crypto: '2.9.0'
  community.docker: '2.7.3'
  community.general: '5.8.5'
  community.grafana: '1.5.3'
  community.hashi_vault: '3.4.0'
  community.mysql: '3.5.1'
  community.network: '4.0.2'
  community.rabbitmq: '1.2.3'
  containers.podman: '1.10.1'
  debops.debops: '3.0.3'
  kubernetes.core: '2.3.2'
  netbox.netbox: '3.11.0'
  openstack.cloud: '1.10.0'
  osism.commons: main
  osism.services: main
  osism.sonic: main
  osism.validations: main
  stackhpc.cephadm: master
