---
ansible_version: '>=2.7,<2.8'
manager_version: 2019.4.0
repository_version: 2019.4.0

osism_projects:
  ara: 1.1.0
  docker: 5:18.09.6
  node_exporter: v0.17.0

docker_images:
  adminer: 4.7
  alertmanager: v0.15.3
  aptly: 1.4.0
  ara_server: 1.1.0
  ara_web: 1.0.0
  blackbox-exporter: v0.12.0
  cadvisor: v0.31.0
  ceph_exporter: 2.0.1-luminous
  cobbler: 2.8
  haproxy_exporter: v0.9.0
  installer: 2019.4.0
  mariadb: 10.4
  memcached_exporter: v0.5.0
  mysqld_exporter: v0.11.0
  nexus: 3.19.0
  nginx: 1.17
  node_exporter: v0.17.0
  phpmyadmin: 4.9
  prometheus: v2.5.0
  redis: 5.0
  registry: 2.7

ansible_roles:
  ANXS.apt: f602ba7e88abfbb3af6679a8ca47207dc3e9d9c4
  ANXS.timezone: 9a77595bf89fc2c255c7c36c18a9cb113911144d
  ANXS.utilities: 8ec75691a6021aa0ba18214bdcba22242c2c5c10
  hardening: 3b95e7fc03310ac127be6a7542eb62c7c9e58777
  osism.cobbler: v2019.4.0
  osism.cockpit: v2019.4.0
  osism.common: v2019.4.0
  osism.chrony: v2019.4.0
  osism.configuration: v2019.4.0
  osism.docker: v2019.4.0
  osism.helper: v2019.4.0
  osism.hostname: v2019.4.0
  osism.hosts: v2019.4.0
  osism.manager: v2019.4.0
  osism.mirror: v2019.4.0
  osism.monitoring: v2019.4.0
  osism.network-interfaces: v2019.4.0
  osism.operator: v2019.4.0
  osism.prometheus-exporter: v2019.4.0
  osism.prometheus: v2019.4.0
  osism.proxy: v2019.4.0
  osism.repository: v2019.4.0
  osism.resolvconf: v2019.4.0
