---
manager_version: 10.0.0
ansible_version: 11.10.0
ansible_core_version: 2.18.9
defaults_version: v0.20260319.0
generics_version: v0.20260319.0
manager_playbooks_version: v0.20260312.0
operations_version: v0.20250530.0
playbooks_version: v0.20260320.0
osism_projects:
  ara: 1.7.3
  docker: 5:27.5.1
  osism: 0.20260320.0
  k3s: v1.34.2+k3s1
docker_images:
  adminer: 5.4.2
  alerta: 9.0.4
  ara_server: 1.7.3
  cgit: 1.2.3
  dnsdist: 1.9.8
  dnsmasq: '2.91'
  homer: v25.11.1
  inventory_reconciler: 0.20260322.0
  fleet: v4.82.0
  gnmic: 0.41.0
  mariadb: 11.8.4
  memcached: 1.6.39-alpine
  netbox: v4.3.5
  nexus: 3.87.0
  nginx: 1.29.3-alpine
  osism: 0.20260320.0
  osism_ansible: 0.20260322.0
  osism_kubernetes: 0.20260322.0
  opentelemetry_collector: 0.146.1
  pgautoupgrade: 16-alpine
  phpmyadmin: 5.2.3
  pushgateway: v1.11.2
  postgres: 16.11-alpine
  redis: 7.4.7-alpine
  registry: '3.0'
  scaphandre: 1.0.2
  squid: 6.1-23.10_beta
  stepca: 0.29.0
  syft: v1.42.1
  openstack_database_exporter: v0.4.2
  tempest: latest
  traefik: v3.5.0
  sonic_vs: latest
  substation: latest
  vault: 1.21.2
  kolla_ansible: 0.20260328.0
  ceph_ansible: 0.20260322.0
  kolla: 0.20260328.0
ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: v1.8.1
  ubuntu22_cis: 2.0.3
ansible_collections:
  ansible.netcommon: 8.4.0
  ansible.posix: 2.1.0
  ansible.utils: 6.0.1
  cloud.common: 5.0.0
  community.crypto: 3.1.1
  community.docker: 5.0.6
  community.general: 11.4.5
  community.grafana: 2.3.0
  community.hashi_vault: 7.1.0
  community.mysql: 4.2.0
  community.network: 5.1.0
  community.rabbitmq: 1.6.0
  community.zabbix: 4.1.1
  containers.podman: 1.19.0
  debops.debops: 3.3.0
  fortinet.fortios: 2.5.0
  netbox.netbox: 3.22.0
  openstack.cloud: 2.5.0
  osism.commons: 0.20260318.0
  osism.services: 0.20260319.0
  osism.validations: 0.20260318.0
  purestorage.flasharray: 1.42.0
