---
ansible_version: '10.3.0'
ansible_core_version: '2.17.3'

defaults_version: 'v0.20240904.0'
generics_version: 'v0.20240904.0'
manager_playbooks_version: 'v0.20240904.0'
manager_version: 8.0.0-rc.3
operations_version: 'v0.20240904.0'
playbooks_version: 'v0.20240904.0'

osism_projects:
  ara: '1.7.1'
  docker: '5:26.1.4'
  osism: '0.20240904.0'
  k3s: 'v1.30.3+k3s1'

docker_images:
  adminer: '4.8.1'
  alerta: '9.0.3'
  ara_server: '1.7.1'
  cgit: '1.2.3'
  dnsdist: '1.9.6'
  homer: 'v24.05.1'
  inventory_reconciler: '8.0.0-rc.3'
  fleet: 'v4.55.1'
  keycloak: '19.0.3-legacy'
  mariadb: '11.5.2'
  memcached: '1.6.29-alpine'
  netbox: 'v4.0.9'
  nexus: '3.71.0'
  nginx: '1.27.1-alpine'
  osism: '0.20240904.0'
  phpmyadmin: '5.2.1'
  pushgateway: 'v1.9.0'
  postgres: '16.4-alpine'
  redis: '7.4.0-alpine'
  registry: '2.8'
  rook_ceph: 'v18.2.2-20240521'
  rook_operator: 'v1.15.0'
  scaphandre: '1.0.0'
  squid: '6.1-23.10_beta'
  openstack_database_exporter: 'v0.4.2'
  tempest: 'latest'
  traefik: 'v3.1.2'
  vault: '1.17.3'

ansible_roles:
  geerlingguy.certbot: '5.2.0'
  geerlingguy.dotfiles: 89067b23d0c564da4799e364686f6632a9fdc813
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: 'v1.7.1'
  proxmox: 'v1.8.1'
  ubuntu22_cis: '1.4.1'

ansible_collections:
  ansible.netcommon: '7.0.0'
  ansible.posix: '1.5.4'
  ansible.utils: '5.1.0'
  cloud.common: '4.0.0'
  community.crypto: '2.21.1'
  community.docker: '3.12.1'
  community.general: '9.3.0'
  community.grafana: '2.1.0'
  community.hashi_vault: '6.2.0'
  community.mysql: '3.10.0'
  community.network: '5.0.3'
  community.rabbitmq: '1.3.0'
  community.zabbix: '3.1.1'
  containers.podman: '1.15.4'
  debops.debops: '3.1.0'
  kubernetes.core: '5.0.0'
  netbox.netbox: '3.19.1'
  openstack.cloud: '2.2.0'
  osism.commons: '0.20240904.0'
  osism.services: '0.20240904.0'
  osism.validations: '0.20240904.0'

helm_chart_repositories:
  bitnami: https://charts.bitnami.com/bitnami
  cnpg: https://cloudnative-pg.github.io/charts
  codecentric: https://codecentric.github.io/helm-charts
  dnationcloud: https://dnationcloud.github.io/helm-hub
  mariadb-operator: https://mariadb-operator.github.io/mariadb-operator
  rook-release: https://charts.rook.io/release
