---
ansible_version: 5.5.0
defaults_version: ed2b2ffa8a32a5b5fdc060a44d17f12655d6cbcf
generics_version: 4cc73a476d4566bc153a58af4a4fa6ed304997c8
manager_version: 3.0.0
operations_version: 1cc3699edeb00ac2e0b7c3eaf0de800b8e02fb0f
playbooks_version: 1c1a5bca72c7f6040db68013394ef816a8cee7eb

osism_projects:
  ara: 1.5.7
  # renovate: datasource=github-releases depName=moby/moby
  docker: 5:20.10.13

docker_images:
  # renovate: datasource=docker depName=adminer
  adminer: 4.8.1
  # renovate: datasource=docker depName=alerta/alerta-web
  alerta: 8.7.0
  # renovate: datasource=docker depName=quay.io/osism/ara-server
  ara_server: 1.5.7
  # renovate: datasource=docker depName=clearlinux/cgit
  cgit: latest
  # renovate: datasource=docker depName=quay.io/osism/dnsdist
  dnsdist: 1.6.1
  # renovate: datasource=docker depName=quay.io/osism/homer
  homer: 21.09.2
  inventory_reconciler: 3.0.0
  # renovate: datasource=docker depName=quay.io/keycloak/keycloak
  keycloak: 17.0.0-legacy
  # renovate: datasource=docker depName=mariadb
  mariadb: 10.8.2
  # renovate: datasource=docker depName=quay.io/osism/netbox
  netbox: v3.1.9-ldap
  # renovate: datasource=docker depName=quay.io/osism/nexus
  nexus: 3.38.0
  # renovate: datasource=docker depName=nginx
  nginx: 1.21.6-alpine
  osism: 0.2.0
  # renovate: datasource=docker depName=phpmyadmin/phpmyadmin
  phpmyadmin: 5.1.3
  # renovate: datasource=docker depName=postgres
  postgres: 14.2-alpine
  # renovate: datasource=docker depName=redis
  redis: 6.2.6-alpine
  # renovate: datasource=docker depName=registry
  registry: '2.8'
  # renovate: datasource=docker depName=traefik
  traefik: v2.6.1
  # renovate: datasource=docker depName=hashicorp/vault
  vault: 1.9.4
  # renovate: datasource=docker depName=zookeeper
  zookeeper: 3.7.0
  # renovate: datasource=docker depName=zuul/zuul-client
  zuul_client: 5.0.0
  # renovate: datasource=docker depName=zuul/zuul-executor
  zuul_executor: 5.0.0
  # renovate: datasource=docker depName=zuul/nodepool-builder
  zuul_nodepool_builder: 5.0.0
  # renovate: datasource=docker depName=zuul/nodepool-launcher
  zuul_nodepool_launcher: 5.0.0
  # renovate: datasource=docker depName=zuul/zuul-scheduler
  zuul_scheduler: 5.0.0
  # renovate: datasource=docker depName=zuul/zuul-web
  zuul_web: 5.0.0

ansible_roles:
  geerlingguy.certbot: eb4647ed9c5be8a90b2ded762e200cf667740efc
  geerlingguy.dotfiles: d737f14972151f21fb775382a0d7e6f564f8ba5c
  hardening: abef57cf7c3da03f25f942e6ddb7f25afd7fda5f
  stackhpc.libvirt_host: a4f0dcc3e94c32a3c32c00b6acd83c406e693a44
  stackhpc.libvirt_vm: 3702892869e82ad90561cb9482a5f71944a59cdf
  stackhpc.luks: 8c4b5f472ab0aef3d2a776d4fcd37ca17c6eac05
  stackhpc.systemd_networkd: d753f616849a19c034983cf3cea9200e1cda438f

ansible_collections:
  ansible.netcommon: 2.6.1
  ansible.posix: 1.3.0
  arista.cvp: 3.3.1
  arista.eos: 4.1.1
  community.general: 4.6.0
  community.network: 3.1.0
  community.zabbix: 1.5.1
  debops.debops: 3.0.1
  netbox.netbox: 3.6.0
  openstack.cloud: 1.7.2
  osism.commons: 0.7.0
  osism.services: 0.8.0
  osism.validations: 0.1.0
  stackhpc.cephadm: 1e746e11cd3810dd62eb915c9c513291b38bc912
  juniper.device: 1.0.1
