---
manager_version: 9.3.1
ansible_version: 11.10.0
ansible_core_version: 2.18.9
defaults_version: v0.20250902.0
generics_version: v0.20250915.0
manager_playbooks_version: v0.20250602.0
operations_version: v0.20250530.0
playbooks_version: v0.20250902.0
osism_projects:
  ara: 1.7.3
  docker: 5:27.5.1
  osism: 0.20250919.0
  k3s: v1.33.4+k3s1
docker_images:
  adminer: 5.4.0
  alerta: 9.0.4
  ara_server: 1.7.3
  cgit: 1.2.3
  dnsdist: 1.9.8
  dnsmasq: '2.91'
  homer: v25.08.1
  inventory_reconciler: 0.20250920.0
  fleet: v4.73.1
  gnmic: 0.41.0
  mariadb: 11.8.3
  memcached: 1.6.39-alpine
  netbox: v4.3.5
  nexus: 3.83.2
  nginx: 1.29.1-alpine
  osism: 0.20250919.0
  osism_ansible: 0.20250920.0
  osism_kubernetes: 0.20250920.0
  opentelemetry_collector: 0.135.0
  pgautoupgrade: 16-alpine
  phpmyadmin: 5.2.2
  pushgateway: v1.11.1
  postgres: 16.10-alpine
  redis: 7.4.5-alpine
  registry: '3.0'
  scaphandre: 1.0.2
  squid: 6.1-23.10_beta
  syft: v1.33.0
  openstack_database_exporter: v0.4.2
  tempest: latest
  traefik: v3.5.0
  sonic_vs: latest
  vault: 1.20.3
  kolla_ansible: 0.20250920.0
  ceph_ansible: 0.20250920.0
  kolla: 0.20250916.0
ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: v1.7.1
  ubuntu22_cis: 2.0.1
ansible_collections:
  ansible.netcommon: 8.1.0
  ansible.posix: 2.1.0
  ansible.utils: 6.0.0
  cloud.common: 5.0.0
  community.crypto: 3.0.3
  community.docker: 4.7.0
  community.general: 11.3.0
  community.grafana: 2.3.0
  community.hashi_vault: 7.0.0
  community.mysql: 3.16.0
  community.network: 5.1.0
  community.rabbitmq: 1.6.0
  community.zabbix: 4.1.1
  containers.podman: 1.18.0
  debops.debops: 3.2.4
  fortinet.fortios: 2.4.0
  netbox.netbox: 3.21.0
  openstack.cloud: 2.4.1
  osism.commons: 0.20250824.0
  osism.services: 0.20250902.0
  osism.validations: 0.20250902.0
  purestorage.flasharray: 1.38.0
