"""Tests for override_template.parse_override_aliases."""

from osism_drift.override_template import parse_override_aliases

# Representative excerpt from container-image-osism-ansible/files/src/templates/images.yml.j2.
# Embedded at authoring time — not read at test runtime.
_FIXTURE = b"""\
---
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

adminer_tag: "{{ versions['adminer'] }}"
adminer_image: "{{ '{{' }} docker_registry {{ '}}' }}/{{ images['adminer'] }}:{{ '{{' }} adminer_tag {{ '}}' }}"

ara_server_mariadb_tag: "{{ versions['mariadb'] }}"
ara_server_mariadb_image: "{{ '{{' }} docker_registry {{ '}}' }}/{{ images['mariadb'] }}:{{ '{{' }} ara_server_mariadb_tag {{ '}}' }}"

manager_redis_tag: "{{ versions['redis'] }}"
manager_redis_image: "{{ '{{' }} docker_registry {{ '}}' }}/{{ images['redis'] }}:{{ '{{' }} manager_redis_tag {{ '}}' }}"

osism_tag: "{{ versions['osism'] }}"
osism_image: "{{ '{{' }} docker_registry_ansible {{ '}}' }}/{{ images['osism'] }}:{{ '{{' }} osism_tag {{ '}}' }}"

nexus_tag: "{{ versions['nexus'] }}"
nexus_image: "{{ '{{' }} docker_registry_nexus {{ '}}' }}/{{ images['nexus'] }}:{{ '{{' }} nexus_tag {{ '}}' }}"
"""

_EXPECTED_ALIASES = {"adminer", "ara_server_mariadb", "manager_redis", "osism", "nexus"}


def test_returns_tag_aliases_only():
    result = parse_override_aliases(_FIXTURE)
    assert result == _EXPECTED_ALIASES


def test_ignores_image_lines():
    result = parse_override_aliases(_FIXTURE)
    assert not any(a.endswith("_image") for a in result)


def test_empty_input():
    assert parse_override_aliases(b"") == set()


def test_comment_and_blank_lines_ignored():
    snippet = b"# adminer_tag: would-not-match\nadminer_tag: foo\n"
    result = parse_override_aliases(snippet)
    assert result == {"adminer"}
