"""Tests for versions_template.parse_versions_map (osism-ansible's versions.yml.j2)."""

import pytest
from osism_drift.source import SourceError
from osism_drift.versions_template import parse_versions_keys, parse_versions_map

# Excerpt of container-image-osism-ansible files/src/templates/versions.yml.j2.
# Embedded at authoring time -- not read at test runtime.
_FIXTURE = b"""\
---
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

docker_version: "{{ docker_version }}"
manager_version: "{{ version }}"
{% if version != "latest" -%}
cephclient_version: "{{ cephclient_version }}"
{% endif %}
{% if 'adminer' in versions -%}
adminer_tag: "{{ versions['adminer'] }}"
{% endif -%}
{% if 'opentelemetry_collector' in versions -%}
opentelemetry_collector_version: "{{ versions['opentelemetry_collector'] }}"
{% endif -%}
{% if 'tempest' in versions -%}
tempest_osism_tag: "{{ versions['tempest'] }}"
{% endif -%}
"""


def test_returns_variable_to_release_key():
    assert parse_versions_map(_FIXTURE) == {
        "adminer_tag": "adminer",
        "opentelemetry_collector_version": "opentelemetry_collector",
        "tempest_osism_tag": "tempest",
    }


def test_plain_variables_are_not_pins():
    result = parse_versions_map(_FIXTURE)
    assert "docker_version" not in result
    assert "cephclient_version" not in result


def test_unguarded_pin_line_is_read():
    assert parse_versions_map(b"stepca_tag: \"{{ versions['stepca'] }}\"\n") == {
        "stepca_tag": "stepca"
    }


def test_guard_naming_another_key_is_an_error():
    body = (
        b"{% if 'adminr' in versions -%}\n"
        b"adminer_tag: \"{{ versions['adminer'] }}\"\n"
        b"{% endif -%}\n"
    )
    with pytest.raises(SourceError, match="adminr"):
        parse_versions_map(body)


def test_filtered_kolla_style_lines_are_not_pins():
    body = (
        b"kolla_aodh_version: \"{{ versions['aodh']|default(openstack_version) }}\"\n"
    )
    assert parse_versions_map(body) == {}
    assert parse_versions_keys(body) == {"aodh"}


def test_empty_input():
    assert parse_versions_map(b"") == {}
