---
manager_version: 9.1.0
ansible_version: 11.6.0
ansible_core_version: 2.18.6
defaults_version: v0.20250529.0
generics_version: v0.20250530.0
manager_playbooks_version: v0.20250407.0
operations_version: v0.20250530.0
playbooks_version: v0.20250529.0
osism_projects:
  ara: 1.7.2
  docker: 5:27.5.1
  osism: 0.20250530.0
  k3s: v1.30.10+k3s1
docker_images:
  adminer: 5.3.0
  alerta: 9.0.4
  ara_server: 1.7.2
  cgit: 1.2.3
  dnsdist: 1.9.8
  dnsmasq: '2.90'
  homer: v25.05.2
  inventory_reconciler: 0.20250530.0
  fleet: v4.68.0
  mariadb: 11.7.2
  memcached: 1.6.38-alpine
  netbox: v4.2.2
  nexus: 3.80.0
  nginx: 1.28.0-alpine
  osism: 0.20250530.0
  osism_ansible: 0.20250530.0
  osism_kubernetes: 0.20250530.0
  opentelemetry_collector: 0.127.0
  pgautoupgrade: 16-alpine
  phpmyadmin: 5.2.2
  pushgateway: v1.11.1
  postgres: 16.9-alpine
  redis: 7.4.4-alpine
  registry: '3.0'
  scaphandre: 1.0.2
  squid: 6.1-23.10_beta
  syft: v1.26.1
  openstack_database_exporter: v0.4.2
  tempest: latest
  traefik: v3.4.1
  vault: 1.19.5
  kolla_ansible: 0.20250530.0
  ceph_ansible: 0.20250530.0
ansible_roles:
  geerlingguy.certbot: master
  geerlingguy.dotfiles: master
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: v1.7.1
  ubuntu22_cis: 1.4.2
ansible_collections:
  ansible.netcommon: 8.0.0
  ansible.posix: 2.0.0
  ansible.utils: 6.0.0
  cloud.common: 4.1.0
  community.crypto: 2.26.2
  community.docker: 4.6.0
  community.general: 10.7.0
  community.grafana: 2.2.0
  community.hashi_vault: 6.2.0
  community.mysql: 3.14.0
  community.network: 5.1.0
  community.rabbitmq: 1.5.0
  community.zabbix: 3.3.0
  containers.podman: 1.16.3
  debops.debops: 3.2.4
  fortinet.fortios: 2.4.0
  netbox.netbox: 3.21.0
  openstack.cloud: 2.4.1
  osism.commons: 0.20250529.0
  osism.services: 0.20250529.0
  osism.validations: 0.20250529.0
  purestorage.flasharray: 1.34.1
