---
ansible_version: '7.3.0'
ansible_core_version: '2.14.3'

defaults_version: 'v0.20230321.0'
generics_version: 'v0.20230321.0'
manager_version: 5.0.0
operations_version: 'v0.20230312.0'
playbooks_version: 'v0.20230313.0'

osism_projects:
  ara: '1.6.1'
  docker: '5:20.10.23'

docker_images:
  adminer: '4.8.1'
  alerta: '8.7.0'
  ara_server: '1.6.1'
  cgit: '1.2.3'
  dnsdist: '1.6.1'
  homer: 'v23.02.2'
  inventory_reconciler: '5.0.0'
  fleet: 'v4.28.0'
  keycloak: '19.0.3-legacy'
  mariadb: '10.11.2'
  memcached: '1.6.18-alpine'
  netbox: 'v3.4.5'
  nexus: '3.49.0'
  nginx: '1.23.3-alpine'
  docker_openpolicyagent: '0.8'
  openstack_health_monitor: 'v5.0'
  osism: '0.20230313.0'
  patchman: '2.0.13'
  phpmyadmin: '5.2.1'
  postgres: '15.2-alpine'
  redis: '7.0.9-alpine'
  registry: '2.8'
  squid: '5.2-22.04_beta'
  traefik: 'v2.9.8'
  vault: '1.13.0'
  zookeeper: '3.8.1'
  zuul_client: '8.2.0'
  zuul_executor: '8.2.0'
  zuul_nodepool_builder: '8.2.0'
  zuul_nodepool_launcher: '8.2.0'
  zuul_scheduler: '8.2.0'
  zuul_web: '8.2.0'

ansible_roles:
  geerlingguy.certbot: '3d55be0a54dc56d18ef70a7254a2afbc51b463ca'
  geerlingguy.dotfiles: '8963afc862e452589502a9abe0ce01a2ffce4326'
  hardening: 'e77c311442cb1d1ef8caa7df9d9c00471afa75e7'
  stackhpc.libvirt_host: '27144f846d2c088d9de0d633f2ad26060bd8e5e7'
  stackhpc.libvirt_vm: 'fc3687773232a211a57c4cc49c39c46b86c353de'
  stackhpc.luks: '8ef3fad657062eb88ec61b0d6da093da0aa71872'
  stackhpc.systemd_networkd: '2b89668768997253dac6805c51d1affa0364217c'

ansible_collections:
  ansible.netcommon: '5.0.0'
  ansible.posix: '1.5.1'
  ansible.utils: '2.8.0'
  cloud.common: '2.1.2'
  community.crypto: '2.9.0'
  community.docker: '2.7.3'
  community.general: '6.4.0'
  community.grafana: '1.5.3'
  community.hashi_vault: '3.4.0'
  community.mysql: '3.5.1'
  community.network: '5.0.0'
  community.rabbitmq: '1.2.3'
  containers.podman: '1.10.1'
  debops.debops: '3.0.3'
  kubernetes.core: '2.3.2'
  netbox.netbox: '3.11.0'
  openstack.cloud: '2.0.0'
  osism.commons: '0.20230312.0'
  osism.services: '0.20230321.0'
  osism.validations: '0.20230313.0'
  stackhpc.cephadm: '1.13.0'
