#!/bin/bash
#
# Generate changelog input file for Claude
#
# This script collects all commits and diffs between the latest tag (or a
# specified tag) and the previous tag, then creates a file with a prompt
# for Claude to generate a changelog entry.
#
# With --from, it processes all tags from the specified tag onwards,
# generating release notes for each one. If commits exist beyond the last
# tag, a virtual tag with today's date is added automatically.
#
# With --auto, it reads CHANGELOG.md to find the last documented tag,
# then processes all tags after it (including a virtual tag for today
# if there are unreleased commits).
#
# For large releases, commits are processed in batches to avoid prompt
# length limits. Batching is based on diff size, not commit count.
#
# Every commit in a release range is resolved to a reference: #N from the
# commit subject (squash-merge convention), otherwise the pull request
# associated with the commit according to the GitHub API (gh), otherwise
# the commit hash itself. Every generated entry must carry its reference
# as (org/repo#N) or (org/repo@hash). This is verified after the merge
# step; missing references are fixed with an extra Claude pass and, as a
# last resort, repaired or appended deterministically. Entries without any
# reference are removed.
#
# The final entry is reduced to pure changelog content (version header,
# category headers, entries, blank lines); any other line — e.g. model
# commentary like "Note: ..." about batches or its own corrections — is
# stripped deterministically before CHANGELOG.md is touched.
#
# For release preparation: If a tag with today's date is specified but
# doesn't exist yet, the script will use HEAD as reference and collect
# commits from the last existing tag to HEAD.
#
# After all tags have been processed, --commit lets Claude write a commit
# message for the CHANGELOG.md change and commits it on a branch; --pr
# additionally pushes that branch and opens a pull request via gh.
#
# Usage: ./scripts/generate-changelog-input.sh [options] [tag]
#
# Options:
#   -a, --auto         Auto-detect: read last tag from CHANGELOG.md, process all after it
#   -f, --from         Process all tags from this tag onwards
#   -n, --no-run       Only generate the input file(s), do not run Claude
#   -o, --output       Specify output file (default: changelog-input-<tag>.md)
#   -s, --max-size     Max lines per batch (default: 2000)
#   -c, --commit       Commit the CHANGELOG.md change (message generated by Claude)
#   -p, --pr           Like --commit, plus push the branch and open a pull request
#   -h, --help         Show this help message
#
# Examples:
#   ./scripts/generate-changelog-input.sh                     # Use latest tag, run Claude
#   ./scripts/generate-changelog-input.sh v0.20251130.1       # Use specific tag, run Claude
#   ./scripts/generate-changelog-input.sh v9.20251205.0       # Prepare new release (tag doesn't exist yet)
#   ./scripts/generate-changelog-input.sh --auto              # Auto-detect from CHANGELOG.md
#   ./scripts/generate-changelog-input.sh --from v0.20260301.0  # All tags from v0.20260301.0 onwards
#   ./scripts/generate-changelog-input.sh -n                  # Only generate file
#   ./scripts/generate-changelog-input.sh -s 3000             # 3000 lines per batch
#   ./scripts/generate-changelog-input.sh --auto --pr         # Generate, commit and open a PR
#

set -e

# Parse arguments
LATEST_TAG=""
FROM_TAG=""
AUTO_MODE=false
OUTPUT_FILE=""
RUN_CLAUDE=true
MAX_BATCH_SIZE=2000
DO_COMMIT=false
DO_PR=false

# Model used for changelog and commit message generation
CLAUDE_MODEL="claude-sonnet-5"
CLAUDE_EFFORT="xhigh"

show_help() {
    echo "Usage: $0 [options] [tag]"
    echo ""
    echo "Options:"
    echo "  -a, --auto         Auto-detect: read last tag from CHANGELOG.md, process all after it"
    echo "  -f, --from         Process all tags from this tag onwards"
    echo "  -n, --no-run       Only generate the input file(s), do not run Claude"
    echo "  -o, --output       Specify output file (default: changelog-input-<tag>.md)"
    echo "  -s, --max-size     Max lines per batch (default: 2000)"
    echo "  -c, --commit       Commit the CHANGELOG.md change (message generated by Claude)"
    echo "  -p, --pr           Like --commit, plus push the branch and open a pull request"
    echo "  -h, --help         Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                          # Use latest tag, run Claude"
    echo "  $0 v0.20251130.1            # Use specific tag, run Claude"
    echo "  $0 --auto                   # Auto-detect from CHANGELOG.md"
    echo "  $0 --from v0.20260301.0     # All tags from v0.20260301.0 onwards"
    echo "  $0 -n                       # Only generate file"
    echo "  $0 -s 3000                  # 3000 lines per batch"
    echo "  $0 --auto --pr              # Generate, commit and open a PR"
    exit 0
}

while [ $# -gt 0 ]; do
    case "$1" in
        -n|--no-run)
            RUN_CLAUDE=false
            shift
            ;;
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -s|--max-size)
            MAX_BATCH_SIZE="$2"
            shift 2
            ;;
        -a|--auto)
            AUTO_MODE=true
            shift
            ;;
        -f|--from)
            FROM_TAG="$2"
            shift 2
            ;;
        -c|--commit)
            DO_COMMIT=true
            shift
            ;;
        -p|--pr)
            DO_COMMIT=true
            DO_PR=true
            shift
            ;;
        -h|--help)
            show_help
            ;;
        v*)
            LATEST_TAG="$1"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use -h or --help for usage information"
            exit 1
            ;;
    esac
done

if [ "$DO_COMMIT" = true ] && [ "$RUN_CLAUDE" = false ]; then
    echo "Error: --commit/--pr cannot be combined with --no-run (nothing is written to CHANGELOG.md)"
    exit 1
fi

if [ "$DO_PR" = true ] && ! command -v gh >/dev/null 2>&1; then
    echo "Error: --pr requires the GitHub CLI (gh), which was not found"
    exit 1
fi

# Handle --auto mode: read last tag from CHANGELOG.md
if [ "$AUTO_MODE" = true ]; then
    if [ -n "$FROM_TAG" ] || [ -n "$LATEST_TAG" ]; then
        echo "Error: --auto cannot be combined with --from or a specific tag"
        exit 1
    fi

    # Check if CHANGELOG.md exists and has version entries
    LAST_CHANGELOG_TAG=""
    if [ -f "CHANGELOG.md" ] && [ -s "CHANGELOG.md" ]; then
        LAST_CHANGELOG_TAG=$(sed -n 's/^## \[\([^]]*\)\].*/\1/p' CHANGELOG.md | head -1)
    fi

    AUTO_TAGS=()

    if [ -z "$LAST_CHANGELOG_TAG" ]; then
        # No CHANGELOG.md, empty, or no version entries: process all tags
        echo "Auto mode: No version entries found in CHANGELOG.md, processing all tags"

        while IFS= read -r tag; do
            AUTO_TAGS+=("$tag")
        done < <(git tag --sort=version:refname | grep '^v0\.')

        if [ ${#AUTO_TAGS[@]} -eq 0 ]; then
            echo "Error: No tags found in repository"
            exit 1
        fi

        # Check for unreleased commits
        LAST_EXISTING_TAG="${AUTO_TAGS[${#AUTO_TAGS[@]}-1]}"
        COMMITS_AFTER=$(git rev-list --count "$LAST_EXISTING_TAG"..HEAD)
        if [ "$COMMITS_AFTER" -gt 0 ]; then
            TODAY_TAG="v0.$(date +%Y%m%d).0"
            if [ "$LAST_EXISTING_TAG" != "$TODAY_TAG" ]; then
                echo "Note: Found $COMMITS_AFTER commit(s) after $LAST_EXISTING_TAG, adding $TODAY_TAG"
                AUTO_TAGS+=("$TODAY_TAG")
            fi
        fi
    else
        echo "Auto mode: Last tag in CHANGELOG.md is $LAST_CHANGELOG_TAG"

        # Verify this tag exists in git
        if ! git rev-parse "$LAST_CHANGELOG_TAG" >/dev/null 2>&1; then
            echo "Error: Tag '$LAST_CHANGELOG_TAG' from CHANGELOG.md not found in git"
            exit 1
        fi

        # Collect all tags after the last changelog tag
        FOUND=false
        AFTER=false
        while IFS= read -r tag; do
            if [ "$AFTER" = true ]; then
                AUTO_TAGS+=("$tag")
            fi
            if [ "$tag" = "$LAST_CHANGELOG_TAG" ]; then
                FOUND=true
                AFTER=true
            fi
        done < <(git tag --sort=version:refname | grep '^v0\.')

        if [ "$FOUND" = false ]; then
            echo "Error: Tag '$LAST_CHANGELOG_TAG' not found in tag list"
            exit 1
        fi

        # Check if HEAD has commits beyond last existing tag
        if [ ${#AUTO_TAGS[@]} -gt 0 ]; then
            LAST_EXISTING_TAG="${AUTO_TAGS[${#AUTO_TAGS[@]}-1]}"
        else
            LAST_EXISTING_TAG="$LAST_CHANGELOG_TAG"
        fi

        COMMITS_AFTER=$(git rev-list --count "$LAST_EXISTING_TAG"..HEAD)
        if [ "$COMMITS_AFTER" -gt 0 ]; then
            TODAY_TAG="v0.$(date +%Y%m%d).0"
            if [ "$LAST_EXISTING_TAG" != "$TODAY_TAG" ]; then
                echo "Note: Found $COMMITS_AFTER commit(s) after $LAST_EXISTING_TAG, adding $TODAY_TAG"
                AUTO_TAGS+=("$TODAY_TAG")
            fi
        fi
    fi

    if [ ${#AUTO_TAGS[@]} -eq 0 ]; then
        echo "No new tags found. CHANGELOG.md is up to date."
        exit 0
    fi

    # Use the collected tags via FROM_TAG logic path
    FROM_TAG="__auto__"
fi

# Build list of tags to process
TAGS_TO_PROCESS=()

if [ "$FROM_TAG" = "__auto__" ]; then
    TAGS_TO_PROCESS=("${AUTO_TAGS[@]}")

    echo "Tags to process (${#TAGS_TO_PROCESS[@]}):"
    for t in "${TAGS_TO_PROCESS[@]}"; do
        echo "  - $t"
    done
    echo ""
elif [ -n "$FROM_TAG" ]; then
    # Multi-tag mode: process all tags from FROM_TAG onwards
    if ! git rev-parse "$FROM_TAG" >/dev/null 2>&1; then
        echo "Error: Tag '$FROM_TAG' not found"
        exit 1
    fi

    FOUND=false
    while IFS= read -r tag; do
        if [ "$tag" = "$FROM_TAG" ]; then
            FOUND=true
        fi
        if [ "$FOUND" = true ]; then
            TAGS_TO_PROCESS+=("$tag")
        fi
    done < <(git tag --sort=version:refname | grep '^v0\.')

    if [ "$FOUND" = false ]; then
        echo "Error: Tag '$FROM_TAG' not found in tag list"
        exit 1
    fi

    # Check if HEAD has commits beyond last existing tag
    LAST_EXISTING_TAG="${TAGS_TO_PROCESS[${#TAGS_TO_PROCESS[@]}-1]}"
    COMMITS_AFTER=$(git rev-list --count "$LAST_EXISTING_TAG"..HEAD)
    if [ "$COMMITS_AFTER" -gt 0 ]; then
        TODAY_TAG="v0.$(date +%Y%m%d).0"
        if [ "$LAST_EXISTING_TAG" != "$TODAY_TAG" ]; then
            echo "Note: Found $COMMITS_AFTER commit(s) after $LAST_EXISTING_TAG, adding $TODAY_TAG"
            TAGS_TO_PROCESS+=("$TODAY_TAG")
        fi
    fi

    echo "Tags to process (${#TAGS_TO_PROCESS[@]}):"
    for t in "${TAGS_TO_PROCESS[@]}"; do
        echo "  - $t"
    done
    echo ""
else
    # Single-tag mode
    if [ -z "$LATEST_TAG" ]; then
        LATEST_TAG=$(git tag --sort=-version:refname | grep '^v0\.' | head -1)
    fi
    if [ -z "$LATEST_TAG" ]; then
        echo "Error: No tags found in repository"
        exit 1
    fi
    TAGS_TO_PROCESS=("$LATEST_TAG")
fi

# Detect GitHub repository (org/repo) from remote URL
GITHUB_REPO=$(git remote get-url origin 2>/dev/null | sed -E 's#.*github\.com[:/]([^/]+/[^/.]+)(\.git)?$#\1#')
if [ -z "$GITHUB_REPO" ]; then
    echo "Warning: Could not detect GitHub repository from remote URL"
    GITHUB_REPO="osism/unknown"
fi

# GITHUB_REPO with regex metacharacters escaped, for use in grep patterns
GITHUB_REPO_RE=$(printf '%s' "$GITHUB_REPO" | sed 's/[.[\*^$]/\\&/g')

# The GitHub API is used to find the pull request of commits that carry no
# #N reference in their subject (e.g. rebase-merged PRs). Without gh those
# commits fall back to their commit hash as reference.
GH_AVAILABLE=false
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    GH_AVAILABLE=true
else
    echo "Warning: GitHub CLI (gh) not available or not authenticated;"
    echo "         commits without a PR reference in the subject will be referenced by commit hash"
fi

_USER_OUTPUT_FILE="$OUTPUT_FILE"

# Process each tag
for CURRENT_TAG in "${TAGS_TO_PROCESS[@]}"; do
LATEST_TAG="$CURRENT_TAG"

if [ ${#TAGS_TO_PROCESS[@]} -gt 1 ]; then
    echo "========================================"
    echo "Processing tag: $LATEST_TAG"
    echo "========================================"
fi

# Set output file for this tag
if [ -z "$_USER_OUTPUT_FILE" ] || [ -n "$FROM_TAG" ]; then
    OUTPUT_FILE="changelog-input-${LATEST_TAG}.md"
else
    OUTPUT_FILE="$_USER_OUTPUT_FILE"
fi

# Check if tag exists or if we're preparing a new release
TAG_EXISTS=true
COMMIT_REF="$LATEST_TAG"

if ! git rev-parse "$LATEST_TAG" >/dev/null 2>&1; then
    TAG_EXISTS=false

    # Check if the tag matches today's date (format: v*.YYYYMMDD.* or vYYYYMMDD.*)
    TODAY=$(date +%Y%m%d)
    if [[ "$LATEST_TAG" =~ [0-9]*\.?($TODAY)\.[0-9]+ ]] || [[ "$LATEST_TAG" =~ ^v($TODAY)\.[0-9]+$ ]]; then
        echo "Note: Tag '$LATEST_TAG' does not exist yet, but matches today's date."
        echo "      Using HEAD as reference for upcoming release preparation."
        COMMIT_REF="HEAD"
    else
        echo "Error: Tag '$LATEST_TAG' does not exist"
        echo "       (To prepare a new release, use a tag with today's date: $(date +%Y%m%d))"
        exit 1
    fi
fi

# Get the previous tag
if [ "$TAG_EXISTS" = true ]; then
    # Tag exists: get the tag before LATEST_TAG
    PREVIOUS_TAG=$(git tag --sort=-version:refname | grep '^v0\.' | grep -A1 "^${LATEST_TAG}$" | tail -1)
else
    # Tag doesn't exist: use the most recent existing tag
    PREVIOUS_TAG=$(git tag --sort=-version:refname | grep '^v0\.' | head -1)
fi

if [ -z "$PREVIOUS_TAG" ] || [ "$LATEST_TAG" = "$PREVIOUS_TAG" ]; then
    # No previous tag: this is the first tag, use the root commit as base
    PREVIOUS_TAG=$(git rev-list --max-parents=0 HEAD | tail -1)
    FIRST_TAG=true
    echo "Note: No previous tag found before $LATEST_TAG, using initial commit as base"
else
    FIRST_TAG=false
fi

echo "Generating changelog input..."
echo "  Target tag:   $LATEST_TAG"
if [ "$TAG_EXISTS" = false ]; then
    echo "  Commit ref:   $COMMIT_REF (tag not yet created)"
fi
if [ "$FIRST_TAG" = true ]; then
    echo "  Previous tag: (none, using initial commit)"
else
    echo "  Previous tag: $PREVIOUS_TAG"
fi

# Get the date from the tag name (format: v0.YYYYMMDD.X or vX.YYYYMMDD.X)
# Extract YYYYMMDD from tag and convert to YYYY-MM-DD
if [[ "$LATEST_TAG" =~ v[0-9]+\.([0-9]{4})([0-9]{2})([0-9]{2})\.[0-9]+ ]]; then
    TAG_DATE="${BASH_REMATCH[1]}-${BASH_REMATCH[2]}-${BASH_REMATCH[3]}"
elif [ "$TAG_EXISTS" = false ]; then
    # Tag doesn't exist yet, use today's date
    TAG_DATE=$(date +%Y-%m-%d)
else
    # Fallback to tag creation date if tag doesn't match expected format
    TAG_DATE=$(git for-each-ref --format='%(creatordate:short)' "refs/tags/$LATEST_TAG")
fi

# Get list of commits (oldest first for logical order)
COMMITS=()
if [ "$FIRST_TAG" = true ]; then
    # Include all commits from the beginning of the repo up to COMMIT_REF
    while IFS= read -r commit; do
        COMMITS+=("$commit")
    done < <(git log --reverse --format="%h" "$COMMIT_REF")
else
    while IFS= read -r commit; do
        COMMITS+=("$commit")
    done < <(git log --reverse --format="%h" "$PREVIOUS_TAG".."$COMMIT_REF")
fi
TOTAL_COMMITS=${#COMMITS[@]}

echo "  Total commits: $TOTAL_COMMITS"
echo "  Max batch size: $MAX_BATCH_SIZE lines"

# Resolve the reference(s) of every commit in the release range. Order of
# precedence: #N references in the commit subject (squash-merge convention),
# then the pull request associated with the commit according to the GitHub
# API, then the commit hash itself. Pure merge commits without a subject
# reference get no reference and are ignored by the changelog.
#
# COMMIT_REFS holds one line per commit: "<hash> <ref>[ <ref>...]" where a
# ref is "#N" or "@hash". REF_SUBJECTS maps each ref to the subject of the
# first commit carrying it: "<ref>\t<subject>".
echo "  Resolving PR/issue references..."
COMMIT_REFS=""
REF_SUBJECTS=""
for commit in "${COMMITS[@]}"; do
    SUBJECT=$(git log -1 --format='%s' "$commit")
    REFS=$(echo "$SUBJECT" | grep -oE '#[0-9]+' | sort -u | tr '\n' ' ')
    REFS="${REFS% }"

    if [ -z "$REFS" ]; then
        PARENT_COUNT=$(git log -1 --format='%P' "$commit" | wc -w)
        if [ "$PARENT_COUNT" -gt 1 ]; then
            continue
        fi

        if [ "$GH_AVAILABLE" = true ]; then
            PR_NUM=$(gh api "repos/${GITHUB_REPO}/commits/$(git rev-parse "$commit")/pulls" --jq '.[0].number' 2>/dev/null || true)
            if [ -n "$PR_NUM" ]; then
                REFS="#${PR_NUM}"
            fi
        fi

        if [ -z "$REFS" ]; then
            REFS="@${commit}"
        fi
    fi

    COMMIT_REFS+="${commit} ${REFS}"$'\n'
    for ref in $REFS; do
        if ! echo "$REF_SUBJECTS" | grep -q "^${ref}	"; then
            REF_SUBJECTS+="${ref}	${SUBJECT}"$'\n'
        fi
    done
done

# Create the prompt template
PROMPT_TEMPLATE='# Changelog Generation Prompt

Analyze the following Git commits and diffs and create CHANGELOG entries in the following format:

```markdown
### Added
- New features (if any) ('"$GITHUB_REPO"'#123)

### Changed
- Changes to existing features (if any) ('"$GITHUB_REPO"'#456)

### Fixed
- Bug fixes (if any) ('"$GITHUB_REPO"'#789)

### Removed
- Removed features (if any) ('"$GITHUB_REPO"'#101)

### Dependencies
- package-name 1.0.0 → 1.1.0 ('"$GITHUB_REPO"'#102)
```

Important notes:
- Group related commits together
- Ignore pure merge commits
- Write entries in English
- Use concise, understandable descriptions
- Remove empty categories (e.g., if there are no "Removed" items)
- Start each entry with a capital letter
- Do not use periods at the end of entries
- Include dependency updates from Renovate in the "Dependencies" section
- Format dependency updates as: "package-name old_version → new_version" (use → arrow, lowercase package name)
- Each commit below carries a **References:** line; every entry MUST end with the reference(s) of the commit(s) it covers, in parentheses: ('"$GITHUB_REPO"'#123) — this makes it a clickable link on GitHub
- Commits without an associated PR/issue are referenced by commit hash: ('"$GITHUB_REPO"'@abc1234)
- If one entry covers several commits/PRs, append all references at the end of the entry: ('"$GITHUB_REPO"'#123, '"$GITHUB_REPO"'#456)
- NEVER output an entry without a reference; commits without a References line (pure merge commits) must be ignored
- Copy references EXACTLY as given in the References lines; never alter the org/repo part
- Do NOT include a version header (## [v...]) — start directly with ### Added, ### Changed, etc.
- Do NOT include any preamble, explanation, or commentary — output ONLY the raw markdown
- Do NOT add notes or remarks about the input, the batch, or your own decisions — not before, between, or after the entries
- Every non-empty line of your output must be either a category header (### ...) or an entry starting with "- "; each entry is a single line

---

'

# Max lines for a single diff (to prevent oversized commits)
MAX_DIFF_LINES=1500

# Function to get commit content
get_commit_content() {
    local commit="$1"
    local content=""
    local diff_content
    local diff_lines

    content+="## Commit: $commit"$'\n\n'
    content+=$(git log -1 --format="**Author:** %an%n**Date:** %ci%n%n**Message:**%n%s%n%n%b" "$commit")

    # Reference(s) resolved for this commit (see COMMIT_REFS above)
    local refs formatted ref
    refs=$(echo "$COMMIT_REFS" | grep "^${commit} " | cut -d' ' -f2- || true)
    if [ -n "$refs" ]; then
        formatted=""
        for ref in $refs; do
            formatted+="${GITHUB_REPO}${ref} "
        done
        content+=$'\n\n'"**References:** ${formatted% }"
    fi

    content+=$'\n\n### Diff\n\n```diff\n'

    # Get diff and truncate if too large
    diff_content=$(git show --format="" "$commit")
    diff_lines=$(echo "$diff_content" | wc -l)

    if [ "$diff_lines" -gt "$MAX_DIFF_LINES" ]; then
        content+=$(echo "$diff_content" | head -n "$MAX_DIFF_LINES")
        content+=$'\n\n... (diff truncated, was '"$diff_lines"' lines) ...\n'
    else
        content+="$diff_content"
    fi

    content+=$'\n```\n\n---\n\n'

    echo "$content"
}

# Create batches based on size
BATCH_FILES=()
BATCH_NUM=1
CURRENT_BATCH=""
CURRENT_SIZE=0
PROMPT_SIZE=$(echo "$PROMPT_TEMPLATE" | wc -l)

for commit in "${COMMITS[@]}"; do
    COMMIT_CONTENT=$(get_commit_content "$commit")
    COMMIT_SIZE=$(echo "$COMMIT_CONTENT" | wc -l)

    # If adding this commit would exceed the limit, save current batch and start new one
    if [ $((CURRENT_SIZE + COMMIT_SIZE + PROMPT_SIZE)) -gt $MAX_BATCH_SIZE ] && [ -n "$CURRENT_BATCH" ]; then
        BATCH_FILE="${OUTPUT_FILE%.md}-batch${BATCH_NUM}.md"
        BATCH_FILES+=("$BATCH_FILE")

        {
            echo "$PROMPT_TEMPLATE"
            echo "## Release Information"
            echo ""
            echo "- **Version:** $LATEST_TAG"
            echo "- **Date:** $TAG_DATE"
            echo "- **Batch:** $BATCH_NUM"
            echo ""
            echo "---"
            echo ""
            echo "# Commits in this batch"
            echo ""
            echo "$CURRENT_BATCH"
        } > "$BATCH_FILE"

        echo "  Created: $BATCH_FILE ($CURRENT_SIZE lines)"
        BATCH_NUM=$((BATCH_NUM + 1))
        CURRENT_BATCH=""
        CURRENT_SIZE=0
    fi

    # Command substitution strips the trailing newlines of the commit
    # content, so re-add the separator between commit blocks here
    CURRENT_BATCH+="$COMMIT_CONTENT"$'\n\n'
    CURRENT_SIZE=$((CURRENT_SIZE + COMMIT_SIZE))
done

# Save the last batch
if [ -n "$CURRENT_BATCH" ]; then
    BATCH_FILE="${OUTPUT_FILE%.md}-batch${BATCH_NUM}.md"
    BATCH_FILES+=("$BATCH_FILE")

    {
        echo "$PROMPT_TEMPLATE"
        echo "## Release Information"
        echo ""
        echo "- **Version:** $LATEST_TAG"
        echo "- **Date:** $TAG_DATE"
        echo "- **Batch:** $BATCH_NUM"
        echo ""
        echo "---"
        echo ""
        echo "# Commits in this batch"
        echo ""
        echo "$CURRENT_BATCH"
    } > "$BATCH_FILE"

    echo "  Created: $BATCH_FILE ($CURRENT_SIZE lines)"
fi

NUM_BATCHES=${#BATCH_FILES[@]}
echo "  Number of batches: $NUM_BATCHES"

# Create the main output file with header
cat > "$OUTPUT_FILE" << EOF
# Changelog for $LATEST_TAG

**Date:** $TAG_DATE
**Previous Version:** $(if [ "$FIRST_TAG" = true ]; then echo "(initial commit)"; else echo "$PREVIOUS_TAG"; fi)
**Total Commits:** $TOTAL_COMMITS

---

EOF

echo ""
echo "Output files created:"
echo "  Main: $OUTPUT_FILE"
for f in "${BATCH_FILES[@]}"; do
    echo "  Batch: $f"
done

if [ "$RUN_CLAUDE" = true ]; then
    echo ""
    echo "Processing batches with Claude..."
    echo ""

    # Process each batch
    BATCH_RESULTS=()
    for (( batch=0; batch<NUM_BATCHES; batch++ )); do
        BATCH_FILE="${BATCH_FILES[$batch]}"
        echo "Processing batch $((batch+1)) of $NUM_BATCHES..."

        # Run Claude and append output to main file
        RESULT=$(claude --model "$CLAUDE_MODEL" --effort "$CLAUDE_EFFORT" -p "$(cat "$BATCH_FILE")" 2>&1) || true
        BATCH_RESULTS+=("$RESULT")

        echo "" >> "$OUTPUT_FILE"
        echo "## Batch $((batch+1))" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "$RESULT" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    done

    if [ "$NUM_BATCHES" -eq 1 ]; then
        # A single batch needs no merge: prepend the version header
        # deterministically. This also avoids a merge pass that has
        # nothing to merge and is tempted to comment on that fact.
        echo ""
        echo "Single batch, skipping merge step..."
        FINAL_RESULT="## [$LATEST_TAG] - $TAG_DATE"$'\n\n'"$(echo "${BATCH_RESULTS[0]}" | grep -v '^## \[' || true)"
    else

    echo ""
    echo "All batches processed. Now merging results..."
    echo ""

    # Create merge prompt
    MERGE_PROMPT="Merge the following changelog batches into a single, clean changelog entry.

Rules:
- Combine all entries into one cohesive changelog
- Remove duplicate entries
- Group by category (Added, Changed, Fixed, Removed, Dependencies)
- Remove empty categories
- Keep the format consistent
- Preserve ALL references in the format (org/repo#number) or (org/repo@hash) at the end of each entry — no reference from the batches may be lost or altered
- When combining duplicate or related entries, merge their references into one list: (org/repo#123, org/repo#456)
- An entry that has a reference in a batch MUST NOT appear without a reference in the merged result
- Every entry in the merged result MUST carry at least one reference
- Your response MUST start with ## [$LATEST_TAG] - $TAG_DATE
- Do NOT include any preamble, explanation, or commentary — output ONLY the raw markdown
- Do NOT add notes or remarks about the merge process, the batches, or corrections you made — not before, between, or after the entries
- Apart from the version header, every non-empty line must be either a category header (### ...) or an entry starting with \"- \"

$(cat "$OUTPUT_FILE")"

    # Run final merge
    FINAL_RESULT=$(claude --model "$CLAUDE_MODEL" --effort "$CLAUDE_EFFORT" -p "$MERGE_PROMPT" 2>&1) || true

    fi  # NUM_BATCHES

    # Strip any preamble before the first ## [v line
    CLEAN_RESULT=$(echo "$FINAL_RESULT" | sed -n '/^## \[v/,$p')
    if [ -z "$CLEAN_RESULT" ]; then
        CLEAN_RESULT="$FINAL_RESULT"
    fi

    # Ensure that every reference resolved for this release (subject, GitHub
    # API or commit hash, see COMMIT_REFS) appears in the generated entry in
    # its full form org/repo#N or org/repo@hash. The full form is required so
    # that garbled repository names are detected as well.
    EXPECTED_REFS=$(echo "$COMMIT_REFS" | cut -d' ' -f2- | tr ' ' '\n' | grep -v '^$' | sort -u || true)

    ref_subject() {
        echo "$REF_SUBJECTS" | awk -F'\t' -v r="$1" '$1 == r { print $2; exit }'
    }

    find_missing_refs() {
        local ref num
        for ref in $EXPECTED_REFS; do
            case "$ref" in
                \#*)
                    num="${ref#\#}"
                    if ! echo "$CLEAN_RESULT" | grep -qE "${GITHUB_REPO_RE}#${num}([^0-9]|\$)"; then
                        echo "$ref"
                    fi
                    ;;
                @*)
                    if ! echo "$CLEAN_RESULT" | grep -qF "${GITHUB_REPO}${ref}"; then
                        echo "$ref"
                    fi
                    ;;
            esac
        done
    }

    MISSING_REFS=$(find_missing_refs)

    if [ -n "$MISSING_REFS" ]; then
        echo ""
        echo "Warning: Generated entry is missing PR/issue references:"
        MISSING_LIST=""
        for ref in $MISSING_REFS; do
            SUBJECT=$(ref_subject "$ref")
            echo "  - ${GITHUB_REPO}${ref}: $SUBJECT"
            MISSING_LIST+="- ${GITHUB_REPO}${ref}: ${SUBJECT}"$'\n'
        done
        echo "Asking Claude to add the missing references..."

        FIX_PROMPT="The following changelog entry is missing references. Every entry MUST end with its reference(s) in parentheses, in the exact format (${GITHUB_REPO}#number) for PRs/issues or (${GITHUB_REPO}@hash) for direct commits. If one entry covers several PRs, list all references: (${GITHUB_REPO}#123, ${GITHUB_REPO}#456).

The following references of this release are missing or malformed (e.g. a wrong org/repo part) in the entry:
$MISSING_LIST
For each missing reference: if an entry describing this change already exists, append or correct the reference on that entry; otherwise add a new entry with the reference to the appropriate category.

Rules:
- Do not reword existing entries and do not drop any existing references
- Entries without any reference are not allowed: attach the correct reference or, if the entry does not correspond to any change of this release, remove it
- Your response MUST start with ## [$LATEST_TAG] - $TAG_DATE
- Do NOT include any preamble, explanation, or commentary — output ONLY the raw markdown
- Do NOT add notes or remarks about the corrections you made — not before, between, or after the entries

Changelog entry:
$CLEAN_RESULT"

        FIX_RESULT=$(claude --model "$CLAUDE_MODEL" --effort "$CLAUDE_EFFORT" -p "$FIX_PROMPT" 2>&1) || true
        FIX_CLEAN=$(echo "$FIX_RESULT" | sed -n '/^## \[v/,$p')
        if [ -n "$FIX_CLEAN" ]; then
            CLEAN_RESULT="$FIX_CLEAN"
        fi

        MISSING_REFS=$(find_missing_refs)
        if [ -n "$MISSING_REFS" ]; then
            # Last resort: repair or append the missing references
            # deterministically so that no change ends up in the changelog
            # without its reference
            echo "Warning: References still missing after fix attempt, repairing directly:"
            FALLBACK_ENTRIES=""
            for ref in $MISSING_REFS; do
                SUBJECT=$(ref_subject "$ref")
                NUM="${ref#\#}"
                if [ "${ref:0:1}" = "#" ] && echo "$CLEAN_RESULT" | grep -qE "#${NUM}([^0-9]|\$)"; then
                    # The number is present but with a wrong or missing
                    # org/repo part (e.g. a garbled repository name):
                    # normalize it in place
                    CLEAN_RESULT=$(echo "$CLEAN_RESULT" | sed -E \
                        -e "s|[A-Za-z0-9._/-]*#${NUM}([^0-9])|${GITHUB_REPO}#${NUM}\1|g" \
                        -e "s|[A-Za-z0-9._/-]*#${NUM}\$|${GITHUB_REPO}#${NUM}|")
                    echo "  - ${GITHUB_REPO}${ref} (normalized malformed reference)"
                else
                    SUBJECT=$(echo "$SUBJECT" | sed -E "s/ *\(#${NUM}\)//")
                    echo "  - ${GITHUB_REPO}${ref} (appended entry)"
                    FALLBACK_ENTRIES+="- ${SUBJECT} (${GITHUB_REPO}${ref})"$'\n'
                fi
            done
            if [ -n "$FALLBACK_ENTRIES" ]; then
                CLEAN_RESULT="$CLEAN_RESULT"$'\n\n### Changed\n\n'"${FALLBACK_ENTRIES%$'\n'}"
            fi
        else
            echo "All missing references were added"
        fi
    fi

    # The final entry may only consist of the version header, category
    # headers, entries and blank lines. Anything else is model commentary
    # (e.g. "Note: ..." remarks about batches or its own corrections) and
    # must never end up in CHANGELOG.md.
    STRAY_LINES=$(echo "$CLEAN_RESULT" | grep -vE '^(## \[|### |- |[[:space:]]*$)' || true)
    if [ -n "$STRAY_LINES" ]; then
        echo ""
        echo "Warning: Removing lines that are not changelog content:"
        echo "$STRAY_LINES" | sed 's/^/  /'
        CLEAN_RESULT=$(echo "$CLEAN_RESULT" | grep -E '^(## \[|### |- |[[:space:]]*$)' | cat -s)
    fi

    # Reverse check: no entry may remain without a reference. All real
    # changes are covered by the reference checks above, so a reference-less
    # entry is a duplicate or hallucinated and can be dropped safely.
    UNREFERENCED=$(echo "$CLEAN_RESULT" | grep -E '^- ' | grep -vE "${GITHUB_REPO_RE}[#@]" || true)
    if [ -n "$UNREFERENCED" ]; then
        echo ""
        echo "Warning: Removing entries without any reference:"
        echo "$UNREFERENCED" | sed 's/^/  /'
        CLEAN_RESULT=$(echo "$CLEAN_RESULT" | awk -v repo="$GITHUB_REPO" \
            '!/^- / || index($0, repo "#") || index($0, repo "@")')
    fi

    # Write final result
    echo "$CLEAN_RESULT" > "$OUTPUT_FILE"

    echo "Final changelog written to: $OUTPUT_FILE"
    echo ""
    echo "Content:"
    echo "----------------------------------------"
    cat "$OUTPUT_FILE"
    echo "----------------------------------------"

    # Insert into CHANGELOG.md
    if [ ! -f "CHANGELOG.md" ] || [ ! -s "CHANGELOG.md" ]; then
        # No CHANGELOG.md or empty: create with header and insert entry
        # Format TAG_DATE to "Month DD, YYYY" for the header
        STARTED_DATE=$(date -j -f "%Y-%m-%d" "$TAG_DATE" "+%B %d, %Y" 2>/dev/null \
            || date -d "$TAG_DATE" "+%B %d, %Y" 2>/dev/null \
            || echo "$TAG_DATE")
        {
            echo "# Changelog"
            echo ""
            echo "All notable changes to this project will be documented in this file."
            echo ""
            echo "The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),"
            echo "and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)."
            echo ""
            echo "This file was started on ${STARTED_DATE}. Changes prior to this date are not included in the CHANGELOG."
            echo ""
            cat "$OUTPUT_FILE"
            echo ""
        } > CHANGELOG.md
        echo "Created CHANGELOG.md and inserted entry"
    else
        INSERT_LINE=$(grep -n '^## \[v' CHANGELOG.md | head -1 | cut -d: -f1)
        if [ -n "$INSERT_LINE" ]; then
            # Has existing version entries: insert before the first one
            {
                head -n $((INSERT_LINE - 1)) CHANGELOG.md
                cat "$OUTPUT_FILE"
                echo ""
                tail -n +"$INSERT_LINE" CHANGELOG.md
            } > CHANGELOG.md.tmp
            mv CHANGELOG.md.tmp CHANGELOG.md
            echo "Inserted into CHANGELOG.md before existing entries"
        else
            # Minimal changelog (header only, no version entries): append at the end
            {
                cat CHANGELOG.md
                echo ""
                cat "$OUTPUT_FILE"
                echo ""
            } > CHANGELOG.md.tmp
            mv CHANGELOG.md.tmp CHANGELOG.md
            echo "Appended to CHANGELOG.md"
        fi
    fi

    # Cleanup batch files
    for f in "${BATCH_FILES[@]}"; do
        rm -f "$f"
    done
else
    echo ""
    echo "Next steps:"
    echo "  1. Run Claude on each batch file:"
    for f in "${BATCH_FILES[@]}"; do
        echo "     claude --model $CLAUDE_MODEL --effort $CLAUDE_EFFORT -p \"\$(cat $f)\""
    done
    echo "  2. Merge the results into $OUTPUT_FILE"
    echo "  3. Add the generated changelog entry to CHANGELOG.md"
fi

done  # end of TAGS_TO_PROCESS loop

# Commit the CHANGELOG.md change and optionally open a pull request
if [ "$DO_COMMIT" = true ]; then
    echo ""

    if git diff --quiet -- CHANGELOG.md && git diff --cached --quiet -- CHANGELOG.md; then
        echo "No changes in CHANGELOG.md, nothing to commit"
        exit 0
    fi

    TAG_LIST=$(printf '%s, ' "${TAGS_TO_PROCESS[@]}")
    TAG_LIST="${TAG_LIST%, }"
    NEWEST_TAG="${TAGS_TO_PROCESS[${#TAGS_TO_PROCESS[@]}-1]}"

    echo "Generating commit message with Claude..."

    CHANGELOG_DIFF=$(git diff -- CHANGELOG.md; git diff --cached -- CHANGELOG.md)

    COMMIT_PROMPT="Write a git commit message for the following change to CHANGELOG.md.
It adds the release notes for: $TAG_LIST

Rules:
- Subject line: 'changelog: ' followed by a short summary, max 72 characters, imperative mood
- Then a blank line, then a body wrapped at 72 characters
- The body summarises what the release(s) contain, in a few sentences or bullets
- Do NOT repeat the changelog verbatim and do NOT list every entry
- Do NOT add any trailers (no Signed-off-by, no Assisted-by, no Co-authored-by)
- Do NOT include any preamble, explanation, code fences or commentary — output ONLY the raw commit message

Diff:
$CHANGELOG_DIFF"

    COMMIT_MSG=$(claude --model "$CLAUDE_MODEL" --effort "$CLAUDE_EFFORT" -p "$COMMIT_PROMPT" 2>&1) || true

    # Drop code fences and any trailers the model added anyway
    COMMIT_MSG=$(echo "$COMMIT_MSG" \
        | sed '/^```/d' \
        | grep -viE '^(Signed-off-by|Assisted-by|Co-authored-by):' || true)

    if [ -z "$(echo "$COMMIT_MSG" | tr -d '[:space:]')" ]; then
        echo "Warning: Claude returned no commit message, using fallback"
        COMMIT_MSG="changelog: add entry for $TAG_LIST"
    fi

    COMMIT_SUBJECT=$(echo "$COMMIT_MSG" | head -1)

    # Branch off if we are on the default branch
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    BRANCH="$CURRENT_BRANCH"
    if [ "$CURRENT_BRANCH" = "main" ] || [ "$CURRENT_BRANCH" = "master" ]; then
        BRANCH="changelog/${NEWEST_TAG}"
        if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
            git switch "$BRANCH"
        else
            git switch -c "$BRANCH"
        fi
    fi

    # Commit (-s adds Signed-off-by from the git config identity)
    COMMIT_MSG_FILE=$(mktemp)
    {
        echo "$COMMIT_MSG"
        echo ""
        echo "Assisted-by: Claude:$CLAUDE_MODEL"
    } > "$COMMIT_MSG_FILE"

    git add CHANGELOG.md
    git commit -s -F "$COMMIT_MSG_FILE"
    rm -f "$COMMIT_MSG_FILE"

    echo ""
    echo "Committed on branch $BRANCH:"
    git log -1 --format='%B' | sed 's/^/  /'

    if [ "$DO_PR" = true ]; then
        echo "Pushing $BRANCH and creating pull request..."

        git push -u origin "$BRANCH"

        PR_BODY="$(echo "$COMMIT_MSG" | tail -n +2)

Generated with \`$(basename "$0")\` using $CLAUDE_MODEL."

        gh pr create --title "$COMMIT_SUBJECT" --body "$PR_BODY"
    fi
fi
