---
ansible_version: '>=2.9,<2.10'
manager_version: 2020.1.0
repository_version: 2020.1.0

osism_projects:
  ara: 1.4.0
  docker: 5:19.03.8
  mitogen: 0.2.9

docker_images:
  adminer: 4.7
  aptly: 1.4.0
  ara_server: 1.4.0
  ara_web: 1.0.0
  cobbler: 2.8
  installer: 2020.1.0
  mariadb: 10.4
  nexus: 3.23.0
  nginx: 1.18-alpine
  phpmyadmin: 5.0
  redis: 6-alpine
  registry: 2.7

ansible_roles:
  ANXS.apt: f602ba7e88abfbb3af6679a8ca47207dc3e9d9c4
  ANXS.timezone: 9a77595bf89fc2c255c7c36c18a9cb113911144d
  ANXS.utilities: 8ec75691a6021aa0ba18214bdcba22242c2c5c10
  hardening: 2093f503a64f213f58f9cab97a10a6f915a02ce9
  osism.cobbler: v2020.1.0
  osism.cockpit: v2020.1.0
  osism.common: v2020.1.0
  osism.chrony: v2020.1.0
  osism.configuration: v2020.1.0
  osism.docker: v2020.1.0
  osism.helper: v2020.1.0
  osism.hostname: v2020.1.0
  osism.hosts: v2020.1.0
  osism.manager: v2020.1.0
  osism.mirror: v2020.1.0
  osism.netdata: v2020.1.0
  osism.network-interfaces: v2020.1.0
  osism.operator: v2020.1.0
  osism.osquery: master
  osism.podman: master
  osism.proxy: v2020.1.0
  osism.repository: v2020.1.0
  osism.resolvconf: v2020.1.0
