---
ansible_version: '11.1.0'
ansible_core_version: '2.18.1'

defaults_version: 'v0.20241219.0'
generics_version: 'v0.20241206.0'
manager_playbooks_version: 'v0.20240924.0'
manager_version: 8.1.0
operations_version: 'v0.20241219.0'
playbooks_version: 'v0.20241219.0'

osism_projects:
  ara: '1.7.2'
  docker: '5:26.1.4'
  osism: '0.20241219.1'
  k3s: 'v1.30.6+k3s1'

docker_images:
  adminer: '4.8.1'
  alerta: '9.0.4'
  ara_server: '1.7.2'
  cgit: '1.2.3'
  dnsdist: '1.9.6'
  fleet: 'v4.60.1'
  homer: 'v24.05.1'
  inventory_reconciler: '8.1.0'
  keycloak: '19.0.3-legacy'
  mariadb: '11.6.2'
  memcached: '1.6.33-alpine'
  netbox: 'v4.1.7'
  nexus: '3.75.1'
  nginx: '1.27.3-alpine'
  openstack_database_exporter: 'v0.4.2'
  osism: '0.20241219.1'
  pgautoupgrade: '16-alpine'
  phpmyadmin: '5.2.1'
  postgres: '16.6-alpine'
  pushgateway: 'v1.10.0'
  redis: '7.4.1-alpine'
  registry: '2.8'
  rook_ceph: 'v18.2.4-20240724'
  rook_operator: 'v1.15.6'
  scaphandre: '1.0.0'
  squid: '6.1-23.10_beta'
  syft: 'v1.17.0'
  tempest: 'latest'
  traefik: 'v3.2.1'
  vault: '1.18.2'

ansible_roles:
  geerlingguy.certbot: '5.2.0'
  geerlingguy.dotfiles: 89067b23d0c564da4799e364686f6632a9fdc813
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: 'v1.7.1'
  proxmox: 'v1.8.1'
  ubuntu22_cis: '1.4.1'

ansible_collections:
  ansible.netcommon: '7.1.0'
  ansible.posix: '1.6.2'
  ansible.utils: '5.1.2'
  cloud.common: '4.0.0'
  community.crypto: '2.22.3'
  community.docker: '4.1.0'
  community.general: '10.1.0'
  community.grafana: '2.1.0'
  community.hashi_vault: '6.2.0'
  community.mysql: '3.11.0'
  community.network: '5.1.0'
  community.rabbitmq: '1.3.0'
  community.zabbix: '3.2.0'
  containers.podman: '1.16.2'
  debops.debops: '3.2.4'
  kubernetes.core: '5.0.0'
  netbox.netbox: '3.20.0'
  openstack.cloud: '2.2.0'
  osism.commons: '0.20241219.0'
  osism.services: '0.20241219.0'
  osism.validations: '0.20241219.0'

helm_chart_repositories:
  bitnami: https://charts.bitnami.com/bitnami
  cnpg: https://cloudnative-pg.github.io/charts
  codecentric: https://codecentric.github.io/helm-charts
  dnationcloud: https://dnationcloud.github.io/helm-hub
  mariadb-operator: https://mariadb-operator.github.io/mariadb-operator
  rook-release: https://charts.rook.io/release
