---
ansible_version: '8.3.0'
ansible_core_version: '2.15.3'

defaults_version: 'v0.20230901.0'
generics_version: 'v0.20230902.0'
manager_version: '6.0.0a'
operations_version: 'v0.20230901.0'
playbooks_version: 'v0.20230901.0'

osism_projects:
  ara: '1.6.1'
  docker: '5:20.10.24'
  osism: '0.20230902.0'
  k3s: 'v1.27.3+k3s1'

docker_images:
  adminer: '4.8.1'
  alerta: '9.0.1'
  ara_server: '1.6.1'
  cgit: '1.2.3'
  dnsdist: '1.8.0'
  homer: 'v23.05.1'
  inventory_reconciler: '6.0.0a'
  fleet: 'v4.36.0'
  keycloak: '19.0.3-legacy'
  mariadb: '10.11.5'
  memcached: '1.6.21-alpine'
  netbox: 'v3.4.8'
  nexus: '3.59.0'
  nginx: '1.25.2-alpine'
  docker_openpolicyagent: '0.8'
  openstack_health_monitor: 'v5.0'
  osism: '0.20230902.0'
  patchman: '2.0.13'
  phpmyadmin: '5.2.1'
  postgres: '15.4-alpine'
  postgres_upgrade: '14-to-15'
  redis: '7.2.0-alpine'
  registry: '2.8'
  scaphandre: '0.5.0'
  squid: '5.2-22.04_beta'
  traefik: 'v2.10.4'
  vault: '1.14.2'
  zookeeper: '3.8.2'
  zuul_client: '8.3.1'
  zuul_executor: '8.3.1'
  zuul_nodepool_builder: '8.2.0'
  zuul_nodepool_launcher: '8.2.0'
  zuul_scheduler: '8.3.1'
  zuul_web: '8.3.1'

ansible_roles:
  geerlingguy.certbot: 08543f45b226f1c0a012581ca4166dd0b6b9cbf2
  geerlingguy.dotfiles: 20988f9859d15710d90c62dd44336a28f141e831
  hardening: e77c311442cb1d1ef8caa7df9d9c00471afa75e7
  pdns_recursor: 'v1.6.0'
  stackhpc.libvirt_host: 27144f846d2c088d9de0d633f2ad26060bd8e5e7
  stackhpc.libvirt_vm: 0c08b28ce3547878e104adc284e09c947809df50
  stackhpc.luks: 81faff11713675f4e35126587445b52732b02aba
  stackhpc.systemd_networkd: 80ab24aef2ebd63fa64783007ca8fa3707bcf558

ansible_collections:
  ansible.netcommon: '5.1.2'
  ansible.posix: '1.5.4'
  ansible.utils: '2.8.0'
  cloud.common: '2.1.2'
  community.crypto: '2.9.0'
  community.docker: '2.7.3'
  community.general: '7.3.0'
  community.grafana: '1.5.3'
  community.hashi_vault: '3.4.0'
  community.mysql: '3.5.1'
  community.network: '5.0.0'
  community.rabbitmq: '1.2.3'
  containers.podman: '1.10.1'
  debops.debops: '3.0.5'
  kubernetes.core: '2.3.2'
  netbox.netbox: '3.14.0'
  openstack.cloud: '2.1.0'
  osism.commons: '0.20230901.0'
  osism.services: '0.20230901.0'
  osism.validations: '0.20230901.0'
  stackhpc.cephadm: '1.13.1'
