---
name: Update base versions

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install ruaeml.yaml
        run: pip3 install ruamel.yaml

      - name: Update versions
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            python3 src/update-base-versions.py
          COMMIT_EMAIL: 'bot@osism.io'
          COMMIT_MESSAGE: |
            chore: update versions in latest/base.yml

            Signed-off-by: OSISM Bot <bot@osism.io>
          COMMIT_NAME: 'OSISM Bot'
          ONLY_DEFAULT_BRANCH: true
          PR_BRANCH_NAME: 'update-base-versions'
          PR_BRANCH_PREFIX: 'chore/'
          PR_TITLE: 'chore: update versions in latest/base.yml'

      - name: Output base.yml
        run: cat latest/base.yml
